set_property SRC_FILE_INFO {cfile:D:/Repo/hls/lab2/lab2-1.vivado/lab2-1.srcs/constrs_1/new/ILA.xdc rfile:../../../lab2-1.srcs/constrs_1/new/ILA.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[0]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[1]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[2]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[3]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[4]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[5]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[6]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[7]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[8]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[9]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[10]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[11]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[12]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[13]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[14]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[15]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[16]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[17]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[18]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[19]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[20]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[21]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[22]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[23]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[24]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[25]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[26]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[27]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[28]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[29]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[30]} {design_1_i/fir_n11_strm_0/inst/pstrmOutput_TDATA[31]}]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[0]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[1]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[2]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[3]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[4]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[5]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[6]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[7]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[8]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[9]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[10]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[11]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[12]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[13]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[14]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[15]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[16]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[17]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[18]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[19]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[20]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[21]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[22]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[23]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[24]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[25]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[26]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[27]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[28]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[29]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[30]} {design_1_i/fir_n11_strm_0/inst/pstrmInput_TDATA[31]}]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/fir_n11_strm_0/inst/ap_start]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/fir_n11_strm_0/inst/ap_done]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
