// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "top.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic top::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic top::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> top::ap_ST_fsm_state1 = "1";
const sc_lv<8> top::ap_ST_fsm_state2 = "10";
const sc_lv<8> top::ap_ST_fsm_state3 = "100";
const sc_lv<8> top::ap_ST_fsm_state4 = "1000";
const sc_lv<8> top::ap_ST_fsm_state5 = "10000";
const sc_lv<8> top::ap_ST_fsm_state6 = "100000";
const sc_lv<8> top::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> top::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> top::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> top::ap_const_lv32_A = "1010";
const sc_lv<32> top::ap_const_lv32_7 = "111";
const sc_lv<32> top::ap_const_lv32_2 = "10";
const sc_lv<32> top::ap_const_lv32_1 = "1";
const sc_lv<32> top::ap_const_lv32_3 = "11";
const sc_lv<32> top::ap_const_lv32_4 = "100";
const sc_lv<32> top::ap_const_lv32_5 = "101";
const sc_lv<32> top::ap_const_lv32_6 = "110";
const sc_lv<32> top::ap_const_lv32_8 = "1000";
const sc_lv<32> top::ap_const_lv32_9 = "1001";
const bool top::ap_const_boolean_0 = false;
const sc_lv<8> top::ap_const_lv8_1 = "1";
const sc_lv<8> top::ap_const_lv8_2 = "10";
const sc_lv<8> top::ap_const_lv8_4 = "100";
const sc_lv<8> top::ap_const_lv8_8 = "1000";
const sc_lv<8> top::ap_const_lv8_10 = "10000";
const sc_lv<8> top::ap_const_lv8_20 = "100000";
const sc_lv<8> top::ap_const_lv8_40 = "1000000";
const sc_lv<8> top::ap_const_lv8_80 = "10000000";
const sc_lv<1> top::ap_const_lv1_1 = "1";
const sc_lv<8> top::ap_const_lv8_0 = "00000000";
const sc_lv<32> top::ap_const_lv32_10 = "10000";
const sc_lv<32> top::ap_const_lv32_1F = "11111";
const sc_lv<16> top::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> top::ap_const_lv32_F = "1111";
const sc_lv<2> top::ap_const_lv2_2 = "10";
const sc_lv<5> top::ap_const_lv5_0 = "00000";
const sc_lv<5> top::ap_const_lv5_10 = "10000";
const sc_lv<5> top::ap_const_lv5_8 = "1000";
const sc_lv<5> top::ap_const_lv5_18 = "11000";
const sc_lv<4> top::ap_const_lv4_0 = "0000";
const sc_lv<5> top::ap_const_lv5_4 = "100";
const sc_lv<2> top::ap_const_lv2_0 = "00";
const sc_lv<5> top::ap_const_lv5_2 = "10";
const sc_lv<2> top::ap_const_lv2_3 = "11";
const sc_lv<3> top::ap_const_lv3_4 = "100";
const sc_lv<3> top::ap_const_lv3_5 = "101";
const sc_lv<3> top::ap_const_lv3_6 = "110";
const sc_lv<3> top::ap_const_lv3_7 = "111";
const bool top::ap_const_boolean_1 = true;

top::top(sc_module_name name) : sc_module(name), mVcdFile(0) {
    call_ret_i_leading_ones_32_s_fu_340 = new leading_ones_32_s("call_ret_i_leading_ones_32_s_fu_340");
    call_ret_i_leading_ones_32_s_fu_340->ap_ready(call_ret_i_leading_ones_32_s_fu_340_ap_ready);
    call_ret_i_leading_ones_32_s_fu_340->din_V_read(leadone_in_V);
    call_ret_i_leading_ones_32_s_fu_340->ap_return_0(call_ret_i_leading_ones_32_s_fu_340_ap_return_0);
    call_ret_i_leading_ones_32_s_fu_340->ap_return_1(call_ret_i_leading_ones_32_s_fu_340_ap_return_1);
    grp_leading_ones_brutefo_fu_346 = new leading_ones_brutefo("grp_leading_ones_brutefo_fu_346");
    grp_leading_ones_brutefo_fu_346->ap_clk(ap_clk);
    grp_leading_ones_brutefo_fu_346->ap_rst(ap_rst);
    grp_leading_ones_brutefo_fu_346->ap_start(grp_leading_ones_brutefo_fu_346_ap_start);
    grp_leading_ones_brutefo_fu_346->ap_done(grp_leading_ones_brutefo_fu_346_ap_done);
    grp_leading_ones_brutefo_fu_346->ap_idle(grp_leading_ones_brutefo_fu_346_ap_idle);
    grp_leading_ones_brutefo_fu_346->ap_ready(grp_leading_ones_brutefo_fu_346_ap_ready);
    grp_leading_ones_brutefo_fu_346->din_V(leadone_in_V);
    grp_leading_ones_brutefo_fu_346->ap_return_0(grp_leading_ones_brutefo_fu_346_ap_return_0);
    grp_leading_ones_brutefo_fu_346->ap_return_1(grp_leading_ones_brutefo_fu_346_ap_return_1);
    grp_leading_ones_fu_352 = new leading_ones("grp_leading_ones_fu_352");
    grp_leading_ones_fu_352->ap_clk(ap_clk);
    grp_leading_ones_fu_352->ap_rst(ap_rst);
    grp_leading_ones_fu_352->ap_start(grp_leading_ones_fu_352_ap_start);
    grp_leading_ones_fu_352->ap_done(grp_leading_ones_fu_352_ap_done);
    grp_leading_ones_fu_352->ap_idle(grp_leading_ones_fu_352_ap_idle);
    grp_leading_ones_fu_352->ap_ready(grp_leading_ones_fu_352_ap_ready);
    grp_leading_ones_fu_352->din_V(leadone_in_V);
    grp_leading_ones_fu_352->ap_return_0(grp_leading_ones_fu_352_ap_return_0);
    grp_leading_ones_fu_352->ap_return_1(grp_leading_ones_fu_352_ap_return_1);
    top_mux_83_8_1_1_U4 = new top_mux_83_8_1_1<1,1,8,8,8,8,8,8,8,8,3,8>("top_mux_83_8_1_1_U4");
    top_mux_83_8_1_1_U4->din0(mux_in_0_V);
    top_mux_83_8_1_1_U4->din1(mux_in_1_V);
    top_mux_83_8_1_1_U4->din2(mux_in_2_V);
    top_mux_83_8_1_1_U4->din3(mux_in_3_V);
    top_mux_83_8_1_1_U4->din4(mux_in_4_V);
    top_mux_83_8_1_1_U4->din5(mux_in_5_V);
    top_mux_83_8_1_1_U4->din6(mux_in_6_V);
    top_mux_83_8_1_1_U4->din7(mux_in_7_V);
    top_mux_83_8_1_1_U4->din8(mux_sel0_V);
    top_mux_83_8_1_1_U4->dout(grp_fu_358_p10);
    top_mux_83_8_1_1_U5 = new top_mux_83_8_1_1<1,1,8,8,8,8,8,8,8,8,3,8>("top_mux_83_8_1_1_U5");
    top_mux_83_8_1_1_U5->din0(mux_in_0_V);
    top_mux_83_8_1_1_U5->din1(mux_in_1_V);
    top_mux_83_8_1_1_U5->din2(mux_in_2_V);
    top_mux_83_8_1_1_U5->din3(mux_in_3_V);
    top_mux_83_8_1_1_U5->din4(mux_in_4_V);
    top_mux_83_8_1_1_U5->din5(mux_in_5_V);
    top_mux_83_8_1_1_U5->din6(mux_in_6_V);
    top_mux_83_8_1_1_U5->din7(mux_in_7_V);
    top_mux_83_8_1_1_U5->din8(tmp_8_fu_531_p9);
    top_mux_83_8_1_1_U5->dout(tmp_8_fu_531_p10);
    top_mux_83_8_1_1_U6 = new top_mux_83_8_1_1<1,1,8,8,8,8,8,8,8,8,3,8>("top_mux_83_8_1_1_U6");
    top_mux_83_8_1_1_U6->din0(mux_in_0_V);
    top_mux_83_8_1_1_U6->din1(mux_in_1_V);
    top_mux_83_8_1_1_U6->din2(mux_in_2_V);
    top_mux_83_8_1_1_U6->din3(mux_in_3_V);
    top_mux_83_8_1_1_U6->din4(mux_in_4_V);
    top_mux_83_8_1_1_U6->din5(mux_in_5_V);
    top_mux_83_8_1_1_U6->din6(mux_in_6_V);
    top_mux_83_8_1_1_U6->din7(mux_in_7_V);
    top_mux_83_8_1_1_U6->din8(mux_sel1_V);
    top_mux_83_8_1_1_U6->dout(tmp_7_fu_554_p10);
    top_mux_83_32_1_1_U7 = new top_mux_83_32_1_1<1,1,32,32,32,32,32,32,32,32,3,32>("top_mux_83_32_1_1_U7");
    top_mux_83_32_1_1_U7->din0(max_in_0_read_reg_1406);
    top_mux_83_32_1_1_U7->din1(max_in_1_read_reg_1416);
    top_mux_83_32_1_1_U7->din2(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U7->din3(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U7->din4(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U7->din5(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U7->din6(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U7->din7(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U7->din8(phi_ln14_1_i_fu_1169_p9);
    top_mux_83_32_1_1_U7->dout(phi_ln14_1_i_fu_1169_p10);
    top_mux_83_32_1_1_U8 = new top_mux_83_32_1_1<1,1,32,32,32,32,32,32,32,32,3,32>("top_mux_83_32_1_1_U8");
    top_mux_83_32_1_1_U8->din0(max_in_0_read_reg_1406);
    top_mux_83_32_1_1_U8->din1(max_in_1_read_reg_1416);
    top_mux_83_32_1_1_U8->din2(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U8->din3(max_in_3);
    top_mux_83_32_1_1_U8->din4(max_in_3);
    top_mux_83_32_1_1_U8->din5(max_in_3);
    top_mux_83_32_1_1_U8->din6(max_in_3);
    top_mux_83_32_1_1_U8->din7(max_in_3);
    top_mux_83_32_1_1_U8->din8(phi_ln14_2_i_fu_1200_p9);
    top_mux_83_32_1_1_U8->dout(phi_ln14_2_i_fu_1200_p10);
    top_mux_83_32_1_1_U9 = new top_mux_83_32_1_1<1,1,32,32,32,32,32,32,32,32,3,32>("top_mux_83_32_1_1_U9");
    top_mux_83_32_1_1_U9->din0(max_in_0_read_reg_1406);
    top_mux_83_32_1_1_U9->din1(max_in_1_read_reg_1416);
    top_mux_83_32_1_1_U9->din2(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U9->din3(max_in_3_read_reg_1447);
    top_mux_83_32_1_1_U9->din4(max_in_4);
    top_mux_83_32_1_1_U9->din5(max_in_4);
    top_mux_83_32_1_1_U9->din6(max_in_4);
    top_mux_83_32_1_1_U9->din7(max_in_4);
    top_mux_83_32_1_1_U9->din8(phi_ln14_3_i_fu_1231_p9);
    top_mux_83_32_1_1_U9->dout(phi_ln14_3_i_fu_1231_p10);
    top_mux_83_32_1_1_U10 = new top_mux_83_32_1_1<1,1,32,32,32,32,32,32,32,32,3,32>("top_mux_83_32_1_1_U10");
    top_mux_83_32_1_1_U10->din0(max_in_0_read_reg_1406);
    top_mux_83_32_1_1_U10->din1(max_in_1_read_reg_1416);
    top_mux_83_32_1_1_U10->din2(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U10->din3(max_in_3_read_reg_1447);
    top_mux_83_32_1_1_U10->din4(max_in_4_read_reg_1465);
    top_mux_83_32_1_1_U10->din5(max_in_5_read_reg_1472);
    top_mux_83_32_1_1_U10->din6(max_in_5_read_reg_1472);
    top_mux_83_32_1_1_U10->din7(max_in_5_read_reg_1472);
    top_mux_83_32_1_1_U10->din8(select_ln13_1_fu_1255_p3);
    top_mux_83_32_1_1_U10->dout(phi_ln14_4_i_fu_1261_p10);
    top_mux_83_32_1_1_U11 = new top_mux_83_32_1_1<1,1,32,32,32,32,32,32,32,32,3,32>("top_mux_83_32_1_1_U11");
    top_mux_83_32_1_1_U11->din0(max_in_0_read_reg_1406);
    top_mux_83_32_1_1_U11->din1(max_in_1_read_reg_1416);
    top_mux_83_32_1_1_U11->din2(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U11->din3(max_in_3_read_reg_1447);
    top_mux_83_32_1_1_U11->din4(max_in_4_read_reg_1465);
    top_mux_83_32_1_1_U11->din5(max_in_5_read_reg_1472);
    top_mux_83_32_1_1_U11->din6(max_in_6_read_reg_1491);
    top_mux_83_32_1_1_U11->din7(max_in_6_read_reg_1491);
    top_mux_83_32_1_1_U11->din8(select_ln14_3_reg_1498);
    top_mux_83_32_1_1_U11->dout(phi_ln14_5_i_fu_1289_p10);
    top_mux_83_32_1_1_U12 = new top_mux_83_32_1_1<1,1,32,32,32,32,32,32,32,32,3,32>("top_mux_83_32_1_1_U12");
    top_mux_83_32_1_1_U12->din0(max_in_0_read_reg_1406);
    top_mux_83_32_1_1_U12->din1(max_in_1_read_reg_1416);
    top_mux_83_32_1_1_U12->din2(max_in_2_read_reg_1426);
    top_mux_83_32_1_1_U12->din3(max_in_3_read_reg_1447);
    top_mux_83_32_1_1_U12->din4(max_in_4_read_reg_1465);
    top_mux_83_32_1_1_U12->din5(max_in_5_read_reg_1472);
    top_mux_83_32_1_1_U12->din6(max_in_6_read_reg_1491);
    top_mux_83_32_1_1_U12->din7(max_in_7);
    top_mux_83_32_1_1_U12->din8(tmp_2_fu_1315_p9);
    top_mux_83_32_1_1_U12->dout(tmp_2_fu_1315_p10);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_and_ln879_1_fu_603_p2);
    sensitive << ( grp_fu_393_p2 );
    sensitive << ( xor_ln879_1_fu_597_p2 );

    SC_METHOD(thread_and_ln879_2_fu_621_p2);
    sensitive << ( grp_fu_399_p2 );
    sensitive << ( xor_ln879_2_fu_615_p2 );

    SC_METHOD(thread_and_ln879_3_fu_639_p2);
    sensitive << ( grp_fu_405_p2 );
    sensitive << ( xor_ln879_3_fu_633_p2 );

    SC_METHOD(thread_and_ln879_4_fu_657_p2);
    sensitive << ( grp_fu_411_p2 );
    sensitive << ( xor_ln879_4_fu_651_p2 );

    SC_METHOD(thread_and_ln879_5_fu_675_p2);
    sensitive << ( grp_fu_417_p2 );
    sensitive << ( xor_ln879_5_fu_669_p2 );

    SC_METHOD(thread_and_ln879_fu_591_p2);
    sensitive << ( grp_fu_387_p2 );
    sensitive << ( xor_ln879_fu_585_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state4_on_subcall_done);
    sensitive << ( mode );
    sensitive << ( grp_leading_ones_brutefo_fu_346_ap_done );
    sensitive << ( grp_leading_ones_fu_352_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_flag_fu_873_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( leadone_in_V );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_grp_fu_381_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_sel_onehot_V );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_grp_fu_387_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_sel_onehot_V );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_grp_fu_393_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_sel_onehot_V );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_grp_fu_399_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_sel_onehot_V );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_grp_fu_405_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_sel_onehot_V );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_grp_fu_411_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_sel_onehot_V );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_grp_fu_417_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_sel_onehot_V );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_grp_fu_423_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_sel_onehot_V );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_grp_fu_429_p2);
    sensitive << ( grp_fu_381_p2 );
    sensitive << ( grp_fu_387_p2 );

    SC_METHOD(thread_grp_leading_ones_brutefo_fu_346_ap_start);
    sensitive << ( grp_leading_ones_brutefo_fu_346_ap_start_reg );

    SC_METHOD(thread_grp_leading_ones_fu_352_ap_start);
    sensitive << ( grp_leading_ones_fu_352_ap_start_reg );

    SC_METHOD(thread_icmp_ln14_1_fu_960_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( max_in_2 );
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( select_ln14_fu_952_p3 );

    SC_METHOD(thread_icmp_ln14_2_fu_1183_p2);
    sensitive << ( max_in_3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( phi_ln14_1_i_fu_1169_p10 );

    SC_METHOD(thread_icmp_ln14_3_fu_1219_p2);
    sensitive << ( max_in_4 );
    sensitive << ( phi_ln14_2_i_reg_1460 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_icmp_ln14_4_fu_1249_p2);
    sensitive << ( max_in_5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( phi_ln14_3_i_fu_1231_p10 );

    SC_METHOD(thread_icmp_ln14_5_fu_1275_p2);
    sensitive << ( max_in_6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( phi_ln14_4_i_fu_1261_p10 );

    SC_METHOD(thread_icmp_ln14_6_fu_1302_p2);
    sensitive << ( max_in_7 );
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( phi_ln14_5_i_fu_1289_p10 );

    SC_METHOD(thread_icmp_ln14_fu_946_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( max_in_0 );
    sensitive << ( max_in_1 );
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_icmp_ln883_1_fu_918_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( trunc_ln3_fu_908_p4 );

    SC_METHOD(thread_icmp_ln883_2_fu_1038_p2);
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( trunc_ln1503_1_reg_1400 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_block_state4_on_subcall_done );

    SC_METHOD(thread_icmp_ln883_3_fu_1073_p2);
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_block_state4_on_subcall_done );
    sensitive << ( trunc_ln1503_2_fu_1063_p4 );

    SC_METHOD(thread_icmp_ln883_fu_890_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( trunc_ln1_fu_880_p4 );

    SC_METHOD(thread_icmp_ln8_1_fu_453_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( max_in_2 );
    sensitive << ( max_in_3 );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_icmp_ln8_2_fu_467_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( m0_1_fu_445_p3 );
    sensitive << ( m1_2_fu_459_p3 );

    SC_METHOD(thread_icmp_ln8_3_fu_481_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( max_in_4 );
    sensitive << ( max_in_5 );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_icmp_ln8_4_fu_495_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( max_in_6 );
    sensitive << ( max_in_7 );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_icmp_ln8_5_fu_509_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( m0_5_fu_487_p3 );
    sensitive << ( m1_5_fu_501_p3 );

    SC_METHOD(thread_icmp_ln8_6_fu_978_p2);
    sensitive << ( m0_3_reg_1341 );
    sensitive << ( m1_6_reg_1347 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_icmp_ln8_fu_439_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( max_in_0 );
    sensitive << ( max_in_1 );
    sensitive << ( mode_read_read_fu_180_p2 );

    SC_METHOD(thread_leadone_out_V);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( call_ret_i_leading_ones_32_s_fu_340_ap_return_1 );
    sensitive << ( grp_leading_ones_brutefo_fu_346_ap_return_1 );
    sensitive << ( grp_leading_ones_fu_352_ap_return_1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ssdm_int_V_write_ass_fu_1137_p3 );
    sensitive << ( ap_block_state4_on_subcall_done );

    SC_METHOD(thread_leadone_out_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_block_state4_on_subcall_done );

    SC_METHOD(thread_leadone_ret);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( call_ret_i_leading_ones_32_s_fu_340_ap_return_0 );
    sensitive << ( grp_leading_ones_brutefo_fu_346_ap_return_0 );
    sensitive << ( grp_leading_ones_fu_352_ap_return_0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_block_state4_on_subcall_done );
    sensitive << ( flag_fu_873_p2 );

    SC_METHOD(thread_leadone_ret_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_block_state4_on_subcall_done );

    SC_METHOD(thread_m0_1_fu_445_p3);
    sensitive << ( max_in_0 );
    sensitive << ( max_in_1 );
    sensitive << ( icmp_ln8_fu_439_p2 );

    SC_METHOD(thread_m0_3_fu_473_p3);
    sensitive << ( m0_1_fu_445_p3 );
    sensitive << ( m1_2_fu_459_p3 );
    sensitive << ( icmp_ln8_2_fu_467_p2 );

    SC_METHOD(thread_m0_5_fu_487_p3);
    sensitive << ( max_in_4 );
    sensitive << ( max_in_5 );
    sensitive << ( icmp_ln8_3_fu_481_p2 );

    SC_METHOD(thread_m1_2_fu_459_p3);
    sensitive << ( max_in_2 );
    sensitive << ( max_in_3 );
    sensitive << ( icmp_ln8_1_fu_453_p2 );

    SC_METHOD(thread_m1_5_fu_501_p3);
    sensitive << ( max_in_6 );
    sensitive << ( max_in_7 );
    sensitive << ( icmp_ln8_4_fu_495_p2 );

    SC_METHOD(thread_m1_6_fu_515_p3);
    sensitive << ( m0_5_fu_487_p3 );
    sensitive << ( m1_5_fu_501_p3 );
    sensitive << ( icmp_ln8_5_fu_509_p2 );

    SC_METHOD(thread_max_out);
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( select_ln8_7_fu_982_p3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_2_fu_1315_p10 );

    SC_METHOD(thread_max_out_ap_vld);
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_mode_read_read_fu_180_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode );

    SC_METHOD(thread_mux_ret_V);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( tmp_8_fu_531_p10 );
    sensitive << ( tmp_V_fu_576_p3 );
    sensitive << ( select_ln6_7_fu_845_p3 );
    sensitive << ( grp_fu_358_p10 );
    sensitive << ( select_ln5_fu_854_p3 );
    sensitive << ( select_ln879_7_fu_1008_p3 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mux_ret_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_or_ln24_1_fu_1079_p2);
    sensitive << ( select_ln24_5_fu_1055_p3 );

    SC_METHOD(thread_or_ln24_2_fu_1121_p2);
    sensitive << ( trunc_ln24_2_fu_1117_p1 );
    sensitive << ( select_ln24_7_fu_1109_p3 );

    SC_METHOD(thread_or_ln24_fu_1049_p2);
    sensitive << ( select_ln24_3_fu_1031_p3 );

    SC_METHOD(thread_or_ln6_1_fu_769_p2);
    sensitive << ( grp_fu_393_p2 );
    sensitive << ( grp_fu_399_p2 );

    SC_METHOD(thread_or_ln6_2_fu_783_p2);
    sensitive << ( grp_fu_405_p2 );
    sensitive << ( grp_fu_411_p2 );

    SC_METHOD(thread_or_ln6_3_fu_797_p2);
    sensitive << ( grp_fu_423_p2 );
    sensitive << ( grp_fu_417_p2 );

    SC_METHOD(thread_or_ln6_4_fu_811_p2);
    sensitive << ( grp_fu_429_p2 );
    sensitive << ( or_ln6_1_fu_769_p2 );

    SC_METHOD(thread_or_ln6_5_fu_825_p2);
    sensitive << ( or_ln6_2_fu_783_p2 );
    sensitive << ( or_ln6_3_fu_797_p2 );

    SC_METHOD(thread_or_ln6_6_fu_839_p2);
    sensitive << ( or_ln6_4_fu_811_p2 );
    sensitive << ( or_ln6_5_fu_825_p2 );

    SC_METHOD(thread_or_ln879_10_fu_993_p2);
    sensitive << ( or_ln879_7_reg_1363 );
    sensitive << ( or_ln879_8_fu_989_p2 );

    SC_METHOD(thread_or_ln879_11_fu_1003_p2);
    sensitive << ( or_ln879_9_reg_1373 );
    sensitive << ( or_ln879_10_fu_993_p2 );

    SC_METHOD(thread_or_ln879_1_fu_609_p2);
    sensitive << ( grp_fu_429_p2 );
    sensitive << ( grp_fu_393_p2 );

    SC_METHOD(thread_or_ln879_2_fu_627_p2);
    sensitive << ( or_ln879_1_fu_609_p2 );
    sensitive << ( grp_fu_399_p2 );

    SC_METHOD(thread_or_ln879_3_fu_645_p2);
    sensitive << ( or_ln879_2_fu_627_p2 );
    sensitive << ( grp_fu_405_p2 );

    SC_METHOD(thread_or_ln879_4_fu_663_p2);
    sensitive << ( or_ln879_3_fu_645_p2 );
    sensitive << ( grp_fu_411_p2 );

    SC_METHOD(thread_or_ln879_5_fu_689_p2);
    sensitive << ( and_ln879_5_fu_675_p2 );
    sensitive << ( and_ln879_4_fu_657_p2 );

    SC_METHOD(thread_or_ln879_6_fu_703_p2);
    sensitive << ( and_ln879_3_fu_639_p2 );
    sensitive << ( and_ln879_2_fu_621_p2 );

    SC_METHOD(thread_or_ln879_7_fu_717_p2);
    sensitive << ( and_ln879_1_fu_603_p2 );
    sensitive << ( and_ln879_fu_591_p2 );

    SC_METHOD(thread_or_ln879_8_fu_989_p2);
    sensitive << ( icmp_ln879_reg_1353 );
    sensitive << ( icmp_ln879_7_reg_1358 );

    SC_METHOD(thread_or_ln879_9_fu_739_p2);
    sensitive << ( or_ln879_5_fu_689_p2 );
    sensitive << ( or_ln879_6_fu_703_p2 );

    SC_METHOD(thread_phi_ln14_1_i_fu_1169_p9);
    sensitive << ( select_ln14_1_reg_1441 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_phi_ln14_2_i_fu_1200_p9);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( select_ln14_2_fu_1189_p3 );

    SC_METHOD(thread_phi_ln14_3_i_fu_1231_p9);
    sensitive << ( zext_ln14_2_reg_1455 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln14_3_fu_1219_p2 );

    SC_METHOD(thread_select_ln13_1_fu_1255_p3);
    sensitive << ( select_ln13_reg_1481 );
    sensitive << ( icmp_ln14_4_reg_1486 );

    SC_METHOD(thread_select_ln13_fu_1224_p3);
    sensitive << ( zext_ln14_2_reg_1455 );
    sensitive << ( icmp_ln14_3_fu_1219_p2 );

    SC_METHOD(thread_select_ln14_1_fu_970_p3);
    sensitive << ( icmp_ln14_1_fu_960_p2 );
    sensitive << ( zext_ln14_fu_966_p1 );

    SC_METHOD(thread_select_ln14_2_fu_1189_p3);
    sensitive << ( select_ln14_1_reg_1441 );
    sensitive << ( icmp_ln14_2_fu_1183_p2 );

    SC_METHOD(thread_select_ln14_3_fu_1281_p3);
    sensitive << ( select_ln13_1_fu_1255_p3 );
    sensitive << ( icmp_ln14_5_fu_1275_p2 );

    SC_METHOD(thread_select_ln14_fu_952_p3);
    sensitive << ( max_in_0 );
    sensitive << ( max_in_1 );
    sensitive << ( icmp_ln14_fu_946_p2 );

    SC_METHOD(thread_select_ln24_1_fu_1017_p3);
    sensitive << ( icmp_ln883_reg_1384 );

    SC_METHOD(thread_select_ln24_2_fu_924_p3);
    sensitive << ( icmp_ln883_1_fu_918_p2 );
    sensitive << ( trunc_ln3_fu_908_p4 );
    sensitive << ( trunc_ln24_fu_904_p1 );

    SC_METHOD(thread_select_ln24_3_fu_1031_p3);
    sensitive << ( icmp_ln883_1_reg_1390 );
    sensitive << ( select_ln24_1_fu_1017_p3 );
    sensitive << ( select_ln25_fu_1024_p3 );

    SC_METHOD(thread_select_ln24_4_fu_1043_p3);
    sensitive << ( trunc_ln24_1_reg_1395 );
    sensitive << ( trunc_ln1503_1_reg_1400 );
    sensitive << ( icmp_ln883_2_fu_1038_p2 );

    SC_METHOD(thread_select_ln24_5_fu_1055_p3);
    sensitive << ( icmp_ln883_2_fu_1038_p2 );
    sensitive << ( select_ln24_3_fu_1031_p3 );
    sensitive << ( or_ln24_fu_1049_p2 );

    SC_METHOD(thread_select_ln24_6_fu_1085_p3);
    sensitive << ( select_ln24_5_fu_1055_p3 );
    sensitive << ( icmp_ln883_3_fu_1073_p2 );
    sensitive << ( or_ln24_1_fu_1079_p2 );

    SC_METHOD(thread_select_ln24_7_fu_1109_p3);
    sensitive << ( icmp_ln883_3_fu_1073_p2 );
    sensitive << ( tmp_4_fu_1093_p3 );
    sensitive << ( tmp_9_fu_1101_p3 );

    SC_METHOD(thread_select_ln24_fu_896_p3);
    sensitive << ( icmp_ln883_fu_890_p2 );
    sensitive << ( trunc_ln1_fu_880_p4 );
    sensitive << ( trunc_ln37_fu_435_p1 );

    SC_METHOD(thread_select_ln25_fu_1024_p3);
    sensitive << ( icmp_ln883_reg_1384 );

    SC_METHOD(thread_select_ln5_fu_854_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_s );

    SC_METHOD(thread_select_ln5_fu_854_p3);
    sensitive << ( mux_in_0_V );
    sensitive << ( mux_in_1_V );
    sensitive << ( select_ln5_fu_854_p0 );

    SC_METHOD(thread_select_ln6_1_fu_761_p3);
    sensitive << ( mux_in_2_V );
    sensitive << ( mux_in_3_V );
    sensitive << ( grp_fu_393_p2 );

    SC_METHOD(thread_select_ln6_2_fu_775_p3);
    sensitive << ( mux_in_4_V );
    sensitive << ( mux_in_5_V );
    sensitive << ( grp_fu_405_p2 );

    SC_METHOD(thread_select_ln6_3_fu_789_p3);
    sensitive << ( mux_in_6_V );
    sensitive << ( mux_in_7_V );
    sensitive << ( grp_fu_417_p2 );

    SC_METHOD(thread_select_ln6_4_fu_803_p3);
    sensitive << ( grp_fu_429_p2 );
    sensitive << ( select_ln6_fu_753_p3 );
    sensitive << ( select_ln6_1_fu_761_p3 );

    SC_METHOD(thread_select_ln6_5_fu_817_p3);
    sensitive << ( or_ln6_2_fu_783_p2 );
    sensitive << ( select_ln6_2_fu_775_p3 );
    sensitive << ( select_ln6_3_fu_789_p3 );

    SC_METHOD(thread_select_ln6_6_fu_831_p3);
    sensitive << ( or_ln6_4_fu_811_p2 );
    sensitive << ( select_ln6_4_fu_803_p3 );
    sensitive << ( select_ln6_5_fu_817_p3 );

    SC_METHOD(thread_select_ln6_7_fu_845_p3);
    sensitive << ( or_ln6_6_fu_839_p2 );
    sensitive << ( select_ln6_6_fu_831_p3 );

    SC_METHOD(thread_select_ln6_fu_753_p3);
    sensitive << ( mux_in_0_V );
    sensitive << ( mux_in_1_V );
    sensitive << ( grp_fu_381_p2 );

    SC_METHOD(thread_select_ln879_1_fu_695_p3);
    sensitive << ( mux_in_3_V );
    sensitive << ( mux_in_4_V );
    sensitive << ( and_ln879_3_fu_639_p2 );

    SC_METHOD(thread_select_ln879_2_fu_709_p3);
    sensitive << ( mux_in_1_V );
    sensitive << ( mux_in_2_V );
    sensitive << ( and_ln879_1_fu_603_p2 );

    SC_METHOD(thread_select_ln879_3_fu_723_p3);
    sensitive << ( mux_in_0_V );
    sensitive << ( mux_in_7_V );
    sensitive << ( grp_fu_381_p2 );

    SC_METHOD(thread_select_ln879_4_fu_731_p3);
    sensitive << ( or_ln879_5_fu_689_p2 );
    sensitive << ( select_ln879_fu_681_p3 );
    sensitive << ( select_ln879_1_fu_695_p3 );

    SC_METHOD(thread_select_ln879_5_fu_745_p3);
    sensitive << ( or_ln879_7_fu_717_p2 );
    sensitive << ( select_ln879_2_fu_709_p3 );
    sensitive << ( select_ln879_3_fu_723_p3 );

    SC_METHOD(thread_select_ln879_6_fu_998_p3);
    sensitive << ( select_ln879_4_reg_1368 );
    sensitive << ( or_ln879_9_reg_1373 );
    sensitive << ( select_ln879_5_reg_1379 );

    SC_METHOD(thread_select_ln879_7_fu_1008_p3);
    sensitive << ( or_ln879_11_fu_1003_p2 );
    sensitive << ( select_ln879_6_fu_998_p3 );

    SC_METHOD(thread_select_ln879_fu_681_p3);
    sensitive << ( mux_in_5_V );
    sensitive << ( mux_in_6_V );
    sensitive << ( and_ln879_5_fu_675_p2 );

    SC_METHOD(thread_select_ln8_7_fu_982_p3);
    sensitive << ( m0_3_reg_1341 );
    sensitive << ( m1_6_reg_1347 );
    sensitive << ( icmp_ln8_6_fu_978_p2 );

    SC_METHOD(thread_select_ln8_fu_523_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_s );

    SC_METHOD(thread_ssdm_int_V_write_ass_fu_1137_p3);
    sensitive << ( tmp_10_fu_1127_p4 );
    sensitive << ( or_ln24_2_fu_1121_p2 );

    SC_METHOD(thread_tmp_10_fu_1127_p4);
    sensitive << ( select_ln24_6_fu_1085_p3 );

    SC_METHOD(thread_tmp_2_fu_1315_p9);
    sensitive << ( select_ln14_3_reg_1498 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln14_6_fu_1302_p2 );

    SC_METHOD(thread_tmp_4_fu_1093_p3);
    sensitive << ( select_ln24_4_fu_1043_p3 );

    SC_METHOD(thread_tmp_8_fu_531_p9);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_sel0_V );
    sensitive << ( mux_sel1_V );
    sensitive << ( select_ln8_fu_523_p0 );

    SC_METHOD(thread_tmp_9_fu_1101_p3);
    sensitive << ( select_ln24_4_fu_1043_p3 );

    SC_METHOD(thread_tmp_V_fu_576_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mux_s );

    SC_METHOD(thread_tmp_V_fu_576_p3);
    sensitive << ( grp_fu_358_p10 );
    sensitive << ( tmp_V_fu_576_p0 );
    sensitive << ( tmp_7_fu_554_p10 );

    SC_METHOD(thread_trunc_ln1503_2_fu_1063_p4);
    sensitive << ( select_ln24_4_fu_1043_p3 );

    SC_METHOD(thread_trunc_ln1_fu_880_p4);
    sensitive << ( leadone_in_V );

    SC_METHOD(thread_trunc_ln24_1_fu_932_p1);
    sensitive << ( select_ln24_2_fu_924_p3 );

    SC_METHOD(thread_trunc_ln24_2_fu_1117_p1);
    sensitive << ( select_ln24_6_fu_1085_p3 );

    SC_METHOD(thread_trunc_ln24_fu_904_p1);
    sensitive << ( select_ln24_fu_896_p3 );

    SC_METHOD(thread_trunc_ln37_fu_435_p1);
    sensitive << ( leadone_in_V );

    SC_METHOD(thread_trunc_ln3_fu_908_p4);
    sensitive << ( select_ln24_fu_896_p3 );

    SC_METHOD(thread_xor_ln879_1_fu_597_p2);
    sensitive << ( grp_fu_429_p2 );

    SC_METHOD(thread_xor_ln879_2_fu_615_p2);
    sensitive << ( or_ln879_1_fu_609_p2 );

    SC_METHOD(thread_xor_ln879_3_fu_633_p2);
    sensitive << ( or_ln879_2_fu_627_p2 );

    SC_METHOD(thread_xor_ln879_4_fu_651_p2);
    sensitive << ( or_ln879_3_fu_645_p2 );

    SC_METHOD(thread_xor_ln879_5_fu_669_p2);
    sensitive << ( or_ln879_4_fu_663_p2 );

    SC_METHOD(thread_xor_ln879_fu_585_p2);
    sensitive << ( grp_fu_381_p2 );

    SC_METHOD(thread_zext_ln14_2_fu_1196_p1);
    sensitive << ( select_ln14_2_fu_1189_p3 );

    SC_METHOD(thread_zext_ln14_fu_966_p1);
    sensitive << ( icmp_ln14_fu_946_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mode );
    sensitive << ( mode_read_read_fu_180_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_block_state4_on_subcall_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000001";
    grp_leading_ones_brutefo_fu_346_ap_start_reg = SC_LOGIC_0;
    grp_leading_ones_fu_352_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "top_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, leadone_in_V, "(port)leadone_in_V");
    sc_trace(mVcdFile, leadone_out_V, "(port)leadone_out_V");
    sc_trace(mVcdFile, leadone_out_V_ap_vld, "(port)leadone_out_V_ap_vld");
    sc_trace(mVcdFile, leadone_ret, "(port)leadone_ret");
    sc_trace(mVcdFile, leadone_ret_ap_vld, "(port)leadone_ret_ap_vld");
    sc_trace(mVcdFile, mux_in_0_V, "(port)mux_in_0_V");
    sc_trace(mVcdFile, mux_in_1_V, "(port)mux_in_1_V");
    sc_trace(mVcdFile, mux_in_2_V, "(port)mux_in_2_V");
    sc_trace(mVcdFile, mux_in_3_V, "(port)mux_in_3_V");
    sc_trace(mVcdFile, mux_in_4_V, "(port)mux_in_4_V");
    sc_trace(mVcdFile, mux_in_5_V, "(port)mux_in_5_V");
    sc_trace(mVcdFile, mux_in_6_V, "(port)mux_in_6_V");
    sc_trace(mVcdFile, mux_in_7_V, "(port)mux_in_7_V");
    sc_trace(mVcdFile, mux_sel_onehot_V, "(port)mux_sel_onehot_V");
    sc_trace(mVcdFile, mux_sel0_V, "(port)mux_sel0_V");
    sc_trace(mVcdFile, mux_sel1_V, "(port)mux_sel1_V");
    sc_trace(mVcdFile, mux_s, "(port)mux_s");
    sc_trace(mVcdFile, mux_ret_V, "(port)mux_ret_V");
    sc_trace(mVcdFile, mux_ret_V_ap_vld, "(port)mux_ret_V_ap_vld");
    sc_trace(mVcdFile, max_in_0, "(port)max_in_0");
    sc_trace(mVcdFile, max_in_1, "(port)max_in_1");
    sc_trace(mVcdFile, max_in_2, "(port)max_in_2");
    sc_trace(mVcdFile, max_in_3, "(port)max_in_3");
    sc_trace(mVcdFile, max_in_4, "(port)max_in_4");
    sc_trace(mVcdFile, max_in_5, "(port)max_in_5");
    sc_trace(mVcdFile, max_in_6, "(port)max_in_6");
    sc_trace(mVcdFile, max_in_7, "(port)max_in_7");
    sc_trace(mVcdFile, max_out, "(port)max_out");
    sc_trace(mVcdFile, max_out_ap_vld, "(port)max_out_ap_vld");
    sc_trace(mVcdFile, mode, "(port)mode");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, mode_read_read_fu_180_p2, "mode_read_read_fu_180_p2");
    sc_trace(mVcdFile, m0_3_fu_473_p3, "m0_3_fu_473_p3");
    sc_trace(mVcdFile, m0_3_reg_1341, "m0_3_reg_1341");
    sc_trace(mVcdFile, m1_6_fu_515_p3, "m1_6_fu_515_p3");
    sc_trace(mVcdFile, m1_6_reg_1347, "m1_6_reg_1347");
    sc_trace(mVcdFile, grp_fu_381_p2, "grp_fu_381_p2");
    sc_trace(mVcdFile, icmp_ln879_reg_1353, "icmp_ln879_reg_1353");
    sc_trace(mVcdFile, grp_fu_423_p2, "grp_fu_423_p2");
    sc_trace(mVcdFile, icmp_ln879_7_reg_1358, "icmp_ln879_7_reg_1358");
    sc_trace(mVcdFile, or_ln879_7_fu_717_p2, "or_ln879_7_fu_717_p2");
    sc_trace(mVcdFile, or_ln879_7_reg_1363, "or_ln879_7_reg_1363");
    sc_trace(mVcdFile, select_ln879_4_fu_731_p3, "select_ln879_4_fu_731_p3");
    sc_trace(mVcdFile, select_ln879_4_reg_1368, "select_ln879_4_reg_1368");
    sc_trace(mVcdFile, or_ln879_9_fu_739_p2, "or_ln879_9_fu_739_p2");
    sc_trace(mVcdFile, or_ln879_9_reg_1373, "or_ln879_9_reg_1373");
    sc_trace(mVcdFile, select_ln879_5_fu_745_p3, "select_ln879_5_fu_745_p3");
    sc_trace(mVcdFile, select_ln879_5_reg_1379, "select_ln879_5_reg_1379");
    sc_trace(mVcdFile, icmp_ln883_fu_890_p2, "icmp_ln883_fu_890_p2");
    sc_trace(mVcdFile, icmp_ln883_reg_1384, "icmp_ln883_reg_1384");
    sc_trace(mVcdFile, icmp_ln883_1_fu_918_p2, "icmp_ln883_1_fu_918_p2");
    sc_trace(mVcdFile, icmp_ln883_1_reg_1390, "icmp_ln883_1_reg_1390");
    sc_trace(mVcdFile, trunc_ln24_1_fu_932_p1, "trunc_ln24_1_fu_932_p1");
    sc_trace(mVcdFile, trunc_ln24_1_reg_1395, "trunc_ln24_1_reg_1395");
    sc_trace(mVcdFile, trunc_ln1503_1_reg_1400, "trunc_ln1503_1_reg_1400");
    sc_trace(mVcdFile, max_in_0_read_reg_1406, "max_in_0_read_reg_1406");
    sc_trace(mVcdFile, max_in_1_read_reg_1416, "max_in_1_read_reg_1416");
    sc_trace(mVcdFile, max_in_2_read_reg_1426, "max_in_2_read_reg_1426");
    sc_trace(mVcdFile, select_ln14_1_fu_970_p3, "select_ln14_1_fu_970_p3");
    sc_trace(mVcdFile, select_ln14_1_reg_1441, "select_ln14_1_reg_1441");
    sc_trace(mVcdFile, max_in_3_read_reg_1447, "max_in_3_read_reg_1447");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, zext_ln14_2_fu_1196_p1, "zext_ln14_2_fu_1196_p1");
    sc_trace(mVcdFile, zext_ln14_2_reg_1455, "zext_ln14_2_reg_1455");
    sc_trace(mVcdFile, phi_ln14_2_i_fu_1200_p10, "phi_ln14_2_i_fu_1200_p10");
    sc_trace(mVcdFile, phi_ln14_2_i_reg_1460, "phi_ln14_2_i_reg_1460");
    sc_trace(mVcdFile, max_in_4_read_reg_1465, "max_in_4_read_reg_1465");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, max_in_5_read_reg_1472, "max_in_5_read_reg_1472");
    sc_trace(mVcdFile, select_ln13_fu_1224_p3, "select_ln13_fu_1224_p3");
    sc_trace(mVcdFile, select_ln13_reg_1481, "select_ln13_reg_1481");
    sc_trace(mVcdFile, icmp_ln14_4_fu_1249_p2, "icmp_ln14_4_fu_1249_p2");
    sc_trace(mVcdFile, icmp_ln14_4_reg_1486, "icmp_ln14_4_reg_1486");
    sc_trace(mVcdFile, max_in_6_read_reg_1491, "max_in_6_read_reg_1491");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, select_ln14_3_fu_1281_p3, "select_ln14_3_fu_1281_p3");
    sc_trace(mVcdFile, select_ln14_3_reg_1498, "select_ln14_3_reg_1498");
    sc_trace(mVcdFile, call_ret_i_leading_ones_32_s_fu_340_ap_ready, "call_ret_i_leading_ones_32_s_fu_340_ap_ready");
    sc_trace(mVcdFile, call_ret_i_leading_ones_32_s_fu_340_ap_return_0, "call_ret_i_leading_ones_32_s_fu_340_ap_return_0");
    sc_trace(mVcdFile, call_ret_i_leading_ones_32_s_fu_340_ap_return_1, "call_ret_i_leading_ones_32_s_fu_340_ap_return_1");
    sc_trace(mVcdFile, grp_leading_ones_brutefo_fu_346_ap_start, "grp_leading_ones_brutefo_fu_346_ap_start");
    sc_trace(mVcdFile, grp_leading_ones_brutefo_fu_346_ap_done, "grp_leading_ones_brutefo_fu_346_ap_done");
    sc_trace(mVcdFile, grp_leading_ones_brutefo_fu_346_ap_idle, "grp_leading_ones_brutefo_fu_346_ap_idle");
    sc_trace(mVcdFile, grp_leading_ones_brutefo_fu_346_ap_ready, "grp_leading_ones_brutefo_fu_346_ap_ready");
    sc_trace(mVcdFile, grp_leading_ones_brutefo_fu_346_ap_return_0, "grp_leading_ones_brutefo_fu_346_ap_return_0");
    sc_trace(mVcdFile, grp_leading_ones_brutefo_fu_346_ap_return_1, "grp_leading_ones_brutefo_fu_346_ap_return_1");
    sc_trace(mVcdFile, grp_leading_ones_fu_352_ap_start, "grp_leading_ones_fu_352_ap_start");
    sc_trace(mVcdFile, grp_leading_ones_fu_352_ap_done, "grp_leading_ones_fu_352_ap_done");
    sc_trace(mVcdFile, grp_leading_ones_fu_352_ap_idle, "grp_leading_ones_fu_352_ap_idle");
    sc_trace(mVcdFile, grp_leading_ones_fu_352_ap_ready, "grp_leading_ones_fu_352_ap_ready");
    sc_trace(mVcdFile, grp_leading_ones_fu_352_ap_return_0, "grp_leading_ones_fu_352_ap_return_0");
    sc_trace(mVcdFile, grp_leading_ones_fu_352_ap_return_1, "grp_leading_ones_fu_352_ap_return_1");
    sc_trace(mVcdFile, grp_leading_ones_brutefo_fu_346_ap_start_reg, "grp_leading_ones_brutefo_fu_346_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_leading_ones_fu_352_ap_start_reg, "grp_leading_ones_fu_352_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_8_fu_531_p10, "tmp_8_fu_531_p10");
    sc_trace(mVcdFile, tmp_V_fu_576_p3, "tmp_V_fu_576_p3");
    sc_trace(mVcdFile, select_ln6_7_fu_845_p3, "select_ln6_7_fu_845_p3");
    sc_trace(mVcdFile, grp_fu_358_p10, "grp_fu_358_p10");
    sc_trace(mVcdFile, select_ln5_fu_854_p3, "select_ln5_fu_854_p3");
    sc_trace(mVcdFile, select_ln879_7_fu_1008_p3, "select_ln879_7_fu_1008_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ssdm_int_V_write_ass_fu_1137_p3, "ssdm_int_V_write_ass_fu_1137_p3");
    sc_trace(mVcdFile, ap_block_state4_on_subcall_done, "ap_block_state4_on_subcall_done");
    sc_trace(mVcdFile, flag_fu_873_p2, "flag_fu_873_p2");
    sc_trace(mVcdFile, select_ln8_7_fu_982_p3, "select_ln8_7_fu_982_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_2_fu_1315_p10, "tmp_2_fu_1315_p10");
    sc_trace(mVcdFile, grp_fu_387_p2, "grp_fu_387_p2");
    sc_trace(mVcdFile, icmp_ln8_fu_439_p2, "icmp_ln8_fu_439_p2");
    sc_trace(mVcdFile, icmp_ln8_1_fu_453_p2, "icmp_ln8_1_fu_453_p2");
    sc_trace(mVcdFile, m0_1_fu_445_p3, "m0_1_fu_445_p3");
    sc_trace(mVcdFile, m1_2_fu_459_p3, "m1_2_fu_459_p3");
    sc_trace(mVcdFile, icmp_ln8_2_fu_467_p2, "icmp_ln8_2_fu_467_p2");
    sc_trace(mVcdFile, icmp_ln8_3_fu_481_p2, "icmp_ln8_3_fu_481_p2");
    sc_trace(mVcdFile, icmp_ln8_4_fu_495_p2, "icmp_ln8_4_fu_495_p2");
    sc_trace(mVcdFile, m0_5_fu_487_p3, "m0_5_fu_487_p3");
    sc_trace(mVcdFile, m1_5_fu_501_p3, "m1_5_fu_501_p3");
    sc_trace(mVcdFile, icmp_ln8_5_fu_509_p2, "icmp_ln8_5_fu_509_p2");
    sc_trace(mVcdFile, select_ln8_fu_523_p0, "select_ln8_fu_523_p0");
    sc_trace(mVcdFile, tmp_8_fu_531_p9, "tmp_8_fu_531_p9");
    sc_trace(mVcdFile, tmp_V_fu_576_p0, "tmp_V_fu_576_p0");
    sc_trace(mVcdFile, tmp_7_fu_554_p10, "tmp_7_fu_554_p10");
    sc_trace(mVcdFile, xor_ln879_fu_585_p2, "xor_ln879_fu_585_p2");
    sc_trace(mVcdFile, grp_fu_429_p2, "grp_fu_429_p2");
    sc_trace(mVcdFile, grp_fu_393_p2, "grp_fu_393_p2");
    sc_trace(mVcdFile, xor_ln879_1_fu_597_p2, "xor_ln879_1_fu_597_p2");
    sc_trace(mVcdFile, or_ln879_1_fu_609_p2, "or_ln879_1_fu_609_p2");
    sc_trace(mVcdFile, grp_fu_399_p2, "grp_fu_399_p2");
    sc_trace(mVcdFile, xor_ln879_2_fu_615_p2, "xor_ln879_2_fu_615_p2");
    sc_trace(mVcdFile, or_ln879_2_fu_627_p2, "or_ln879_2_fu_627_p2");
    sc_trace(mVcdFile, grp_fu_405_p2, "grp_fu_405_p2");
    sc_trace(mVcdFile, xor_ln879_3_fu_633_p2, "xor_ln879_3_fu_633_p2");
    sc_trace(mVcdFile, or_ln879_3_fu_645_p2, "or_ln879_3_fu_645_p2");
    sc_trace(mVcdFile, grp_fu_411_p2, "grp_fu_411_p2");
    sc_trace(mVcdFile, xor_ln879_4_fu_651_p2, "xor_ln879_4_fu_651_p2");
    sc_trace(mVcdFile, or_ln879_4_fu_663_p2, "or_ln879_4_fu_663_p2");
    sc_trace(mVcdFile, grp_fu_417_p2, "grp_fu_417_p2");
    sc_trace(mVcdFile, xor_ln879_5_fu_669_p2, "xor_ln879_5_fu_669_p2");
    sc_trace(mVcdFile, and_ln879_5_fu_675_p2, "and_ln879_5_fu_675_p2");
    sc_trace(mVcdFile, and_ln879_4_fu_657_p2, "and_ln879_4_fu_657_p2");
    sc_trace(mVcdFile, and_ln879_3_fu_639_p2, "and_ln879_3_fu_639_p2");
    sc_trace(mVcdFile, and_ln879_2_fu_621_p2, "and_ln879_2_fu_621_p2");
    sc_trace(mVcdFile, and_ln879_1_fu_603_p2, "and_ln879_1_fu_603_p2");
    sc_trace(mVcdFile, and_ln879_fu_591_p2, "and_ln879_fu_591_p2");
    sc_trace(mVcdFile, or_ln879_5_fu_689_p2, "or_ln879_5_fu_689_p2");
    sc_trace(mVcdFile, select_ln879_fu_681_p3, "select_ln879_fu_681_p3");
    sc_trace(mVcdFile, select_ln879_1_fu_695_p3, "select_ln879_1_fu_695_p3");
    sc_trace(mVcdFile, or_ln879_6_fu_703_p2, "or_ln879_6_fu_703_p2");
    sc_trace(mVcdFile, select_ln879_2_fu_709_p3, "select_ln879_2_fu_709_p3");
    sc_trace(mVcdFile, select_ln879_3_fu_723_p3, "select_ln879_3_fu_723_p3");
    sc_trace(mVcdFile, select_ln6_fu_753_p3, "select_ln6_fu_753_p3");
    sc_trace(mVcdFile, select_ln6_1_fu_761_p3, "select_ln6_1_fu_761_p3");
    sc_trace(mVcdFile, or_ln6_1_fu_769_p2, "or_ln6_1_fu_769_p2");
    sc_trace(mVcdFile, or_ln6_2_fu_783_p2, "or_ln6_2_fu_783_p2");
    sc_trace(mVcdFile, select_ln6_2_fu_775_p3, "select_ln6_2_fu_775_p3");
    sc_trace(mVcdFile, select_ln6_3_fu_789_p3, "select_ln6_3_fu_789_p3");
    sc_trace(mVcdFile, or_ln6_3_fu_797_p2, "or_ln6_3_fu_797_p2");
    sc_trace(mVcdFile, or_ln6_4_fu_811_p2, "or_ln6_4_fu_811_p2");
    sc_trace(mVcdFile, select_ln6_4_fu_803_p3, "select_ln6_4_fu_803_p3");
    sc_trace(mVcdFile, select_ln6_5_fu_817_p3, "select_ln6_5_fu_817_p3");
    sc_trace(mVcdFile, or_ln6_5_fu_825_p2, "or_ln6_5_fu_825_p2");
    sc_trace(mVcdFile, or_ln6_6_fu_839_p2, "or_ln6_6_fu_839_p2");
    sc_trace(mVcdFile, select_ln6_6_fu_831_p3, "select_ln6_6_fu_831_p3");
    sc_trace(mVcdFile, select_ln5_fu_854_p0, "select_ln5_fu_854_p0");
    sc_trace(mVcdFile, trunc_ln1_fu_880_p4, "trunc_ln1_fu_880_p4");
    sc_trace(mVcdFile, trunc_ln37_fu_435_p1, "trunc_ln37_fu_435_p1");
    sc_trace(mVcdFile, select_ln24_fu_896_p3, "select_ln24_fu_896_p3");
    sc_trace(mVcdFile, trunc_ln3_fu_908_p4, "trunc_ln3_fu_908_p4");
    sc_trace(mVcdFile, trunc_ln24_fu_904_p1, "trunc_ln24_fu_904_p1");
    sc_trace(mVcdFile, select_ln24_2_fu_924_p3, "select_ln24_2_fu_924_p3");
    sc_trace(mVcdFile, icmp_ln14_fu_946_p2, "icmp_ln14_fu_946_p2");
    sc_trace(mVcdFile, select_ln14_fu_952_p3, "select_ln14_fu_952_p3");
    sc_trace(mVcdFile, icmp_ln14_1_fu_960_p2, "icmp_ln14_1_fu_960_p2");
    sc_trace(mVcdFile, zext_ln14_fu_966_p1, "zext_ln14_fu_966_p1");
    sc_trace(mVcdFile, icmp_ln8_6_fu_978_p2, "icmp_ln8_6_fu_978_p2");
    sc_trace(mVcdFile, or_ln879_8_fu_989_p2, "or_ln879_8_fu_989_p2");
    sc_trace(mVcdFile, or_ln879_10_fu_993_p2, "or_ln879_10_fu_993_p2");
    sc_trace(mVcdFile, or_ln879_11_fu_1003_p2, "or_ln879_11_fu_1003_p2");
    sc_trace(mVcdFile, select_ln879_6_fu_998_p3, "select_ln879_6_fu_998_p3");
    sc_trace(mVcdFile, select_ln24_1_fu_1017_p3, "select_ln24_1_fu_1017_p3");
    sc_trace(mVcdFile, select_ln25_fu_1024_p3, "select_ln25_fu_1024_p3");
    sc_trace(mVcdFile, icmp_ln883_2_fu_1038_p2, "icmp_ln883_2_fu_1038_p2");
    sc_trace(mVcdFile, select_ln24_3_fu_1031_p3, "select_ln24_3_fu_1031_p3");
    sc_trace(mVcdFile, or_ln24_fu_1049_p2, "or_ln24_fu_1049_p2");
    sc_trace(mVcdFile, select_ln24_4_fu_1043_p3, "select_ln24_4_fu_1043_p3");
    sc_trace(mVcdFile, trunc_ln1503_2_fu_1063_p4, "trunc_ln1503_2_fu_1063_p4");
    sc_trace(mVcdFile, select_ln24_5_fu_1055_p3, "select_ln24_5_fu_1055_p3");
    sc_trace(mVcdFile, icmp_ln883_3_fu_1073_p2, "icmp_ln883_3_fu_1073_p2");
    sc_trace(mVcdFile, or_ln24_1_fu_1079_p2, "or_ln24_1_fu_1079_p2");
    sc_trace(mVcdFile, tmp_4_fu_1093_p3, "tmp_4_fu_1093_p3");
    sc_trace(mVcdFile, tmp_9_fu_1101_p3, "tmp_9_fu_1101_p3");
    sc_trace(mVcdFile, select_ln24_6_fu_1085_p3, "select_ln24_6_fu_1085_p3");
    sc_trace(mVcdFile, trunc_ln24_2_fu_1117_p1, "trunc_ln24_2_fu_1117_p1");
    sc_trace(mVcdFile, select_ln24_7_fu_1109_p3, "select_ln24_7_fu_1109_p3");
    sc_trace(mVcdFile, tmp_10_fu_1127_p4, "tmp_10_fu_1127_p4");
    sc_trace(mVcdFile, or_ln24_2_fu_1121_p2, "or_ln24_2_fu_1121_p2");
    sc_trace(mVcdFile, phi_ln14_1_i_fu_1169_p9, "phi_ln14_1_i_fu_1169_p9");
    sc_trace(mVcdFile, phi_ln14_1_i_fu_1169_p10, "phi_ln14_1_i_fu_1169_p10");
    sc_trace(mVcdFile, icmp_ln14_2_fu_1183_p2, "icmp_ln14_2_fu_1183_p2");
    sc_trace(mVcdFile, select_ln14_2_fu_1189_p3, "select_ln14_2_fu_1189_p3");
    sc_trace(mVcdFile, phi_ln14_2_i_fu_1200_p9, "phi_ln14_2_i_fu_1200_p9");
    sc_trace(mVcdFile, icmp_ln14_3_fu_1219_p2, "icmp_ln14_3_fu_1219_p2");
    sc_trace(mVcdFile, phi_ln14_3_i_fu_1231_p9, "phi_ln14_3_i_fu_1231_p9");
    sc_trace(mVcdFile, phi_ln14_3_i_fu_1231_p10, "phi_ln14_3_i_fu_1231_p10");
    sc_trace(mVcdFile, select_ln13_1_fu_1255_p3, "select_ln13_1_fu_1255_p3");
    sc_trace(mVcdFile, phi_ln14_4_i_fu_1261_p10, "phi_ln14_4_i_fu_1261_p10");
    sc_trace(mVcdFile, icmp_ln14_5_fu_1275_p2, "icmp_ln14_5_fu_1275_p2");
    sc_trace(mVcdFile, phi_ln14_5_i_fu_1289_p10, "phi_ln14_5_i_fu_1289_p10");
    sc_trace(mVcdFile, icmp_ln14_6_fu_1302_p2, "icmp_ln14_6_fu_1302_p2");
    sc_trace(mVcdFile, tmp_2_fu_1315_p9, "tmp_2_fu_1315_p9");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("top.hdltvin.dat");
    mHdltvoutHandle.open("top.hdltvout.dat");
}

top::~top() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete call_ret_i_leading_ones_32_s_fu_340;
    delete grp_leading_ones_brutefo_fu_346;
    delete grp_leading_ones_fu_352;
    delete top_mux_83_8_1_1_U4;
    delete top_mux_83_8_1_1_U5;
    delete top_mux_83_8_1_1_U6;
    delete top_mux_83_32_1_1_U7;
    delete top_mux_83_32_1_1_U8;
    delete top_mux_83_32_1_1_U9;
    delete top_mux_83_32_1_1_U10;
    delete top_mux_83_32_1_1_U11;
    delete top_mux_83_32_1_1_U12;
}

void top::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_leading_ones_brutefo_fu_346_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
             esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1))) {
            grp_leading_ones_brutefo_fu_346_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_leading_ones_brutefo_fu_346_ap_ready.read())) {
            grp_leading_ones_brutefo_fu_346_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_leading_ones_fu_352_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
             esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()))) {
            grp_leading_ones_fu_352_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_leading_ones_fu_352_ap_ready.read())) {
            grp_leading_ones_fu_352_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        icmp_ln14_4_reg_1486 = icmp_ln14_4_fu_1249_p2.read();
        max_in_4_read_reg_1465 = max_in_4.read();
        max_in_5_read_reg_1472 = max_in_5.read();
        select_ln13_reg_1481 = select_ln13_fu_1224_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_7))) {
        icmp_ln879_7_reg_1358 = grp_fu_423_p2.read();
        icmp_ln879_reg_1353 = grp_fu_381_p2.read();
        or_ln879_7_reg_1363 = or_ln879_7_fu_717_p2.read();
        or_ln879_9_reg_1373 = or_ln879_9_fu_739_p2.read();
        select_ln879_4_reg_1368 = select_ln879_4_fu_731_p3.read();
        select_ln879_5_reg_1379 = select_ln879_5_fu_745_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2))) {
        icmp_ln883_1_reg_1390 = icmp_ln883_1_fu_918_p2.read();
        icmp_ln883_reg_1384 = icmp_ln883_fu_890_p2.read();
        trunc_ln1503_1_reg_1400 = select_ln24_2_fu_924_p3.read().range(7, 4);
        trunc_ln24_1_reg_1395 = trunc_ln24_1_fu_932_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_A))) {
        m0_3_reg_1341 = m0_3_fu_473_p3.read();
        m1_6_reg_1347 = m1_6_fu_515_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && !esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()) && !esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_3) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_4) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_5) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_6) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_7) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_8) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_9) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_A))) {
        max_in_0_read_reg_1406 = max_in_0.read();
        max_in_1_read_reg_1416 = max_in_1.read();
        max_in_2_read_reg_1426 = max_in_2.read();
        select_ln14_1_reg_1441 = select_ln14_1_fu_970_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        max_in_3_read_reg_1447 = max_in_3.read();
        phi_ln14_2_i_reg_1460 = phi_ln14_2_i_fu_1200_p10.read();
        zext_ln14_2_reg_1455 = zext_ln14_2_fu_1196_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        max_in_6_read_reg_1491 = max_in_6.read();
        select_ln14_3_reg_1498 = select_ln14_3_fu_1281_p3.read();
    }
}

void top::thread_and_ln879_1_fu_603_p2() {
    and_ln879_1_fu_603_p2 = (grp_fu_393_p2.read() & xor_ln879_1_fu_597_p2.read());
}

void top::thread_and_ln879_2_fu_621_p2() {
    and_ln879_2_fu_621_p2 = (grp_fu_399_p2.read() & xor_ln879_2_fu_615_p2.read());
}

void top::thread_and_ln879_3_fu_639_p2() {
    and_ln879_3_fu_639_p2 = (grp_fu_405_p2.read() & xor_ln879_3_fu_633_p2.read());
}

void top::thread_and_ln879_4_fu_657_p2() {
    and_ln879_4_fu_657_p2 = (grp_fu_411_p2.read() & xor_ln879_4_fu_651_p2.read());
}

void top::thread_and_ln879_5_fu_675_p2() {
    and_ln879_5_fu_675_p2 = (grp_fu_417_p2.read() & xor_ln879_5_fu_669_p2.read());
}

void top::thread_and_ln879_fu_591_p2() {
    and_ln879_fu_591_p2 = (grp_fu_387_p2.read() & xor_ln879_fu_585_p2.read());
}

void top::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void top::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void top::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void top::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void top::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void top::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void top::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void top::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void top::thread_ap_block_state4_on_subcall_done() {
    ap_block_state4_on_subcall_done = ((esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_leading_ones_brutefo_fu_346_ap_done.read())) || (esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_leading_ones_fu_352_ap_done.read())));
}

void top::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void top::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void top::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void top::thread_flag_fu_873_p2() {
    flag_fu_873_p2 = (!leadone_in_V.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(leadone_in_V.read() != ap_const_lv32_0);
}

void top::thread_grp_fu_381_p2() {
    grp_fu_381_p2 = (!mux_sel_onehot_V.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<1>(): sc_lv<1>(mux_sel_onehot_V.read() == ap_const_lv8_1);
}

void top::thread_grp_fu_387_p2() {
    grp_fu_387_p2 = (!mux_sel_onehot_V.read().is_01() || !ap_const_lv8_2.is_01())? sc_lv<1>(): sc_lv<1>(mux_sel_onehot_V.read() == ap_const_lv8_2);
}

void top::thread_grp_fu_393_p2() {
    grp_fu_393_p2 = (!mux_sel_onehot_V.read().is_01() || !ap_const_lv8_4.is_01())? sc_lv<1>(): sc_lv<1>(mux_sel_onehot_V.read() == ap_const_lv8_4);
}

void top::thread_grp_fu_399_p2() {
    grp_fu_399_p2 = (!mux_sel_onehot_V.read().is_01() || !ap_const_lv8_8.is_01())? sc_lv<1>(): sc_lv<1>(mux_sel_onehot_V.read() == ap_const_lv8_8);
}

void top::thread_grp_fu_405_p2() {
    grp_fu_405_p2 = (!mux_sel_onehot_V.read().is_01() || !ap_const_lv8_10.is_01())? sc_lv<1>(): sc_lv<1>(mux_sel_onehot_V.read() == ap_const_lv8_10);
}

void top::thread_grp_fu_411_p2() {
    grp_fu_411_p2 = (!mux_sel_onehot_V.read().is_01() || !ap_const_lv8_20.is_01())? sc_lv<1>(): sc_lv<1>(mux_sel_onehot_V.read() == ap_const_lv8_20);
}

void top::thread_grp_fu_417_p2() {
    grp_fu_417_p2 = (!mux_sel_onehot_V.read().is_01() || !ap_const_lv8_40.is_01())? sc_lv<1>(): sc_lv<1>(mux_sel_onehot_V.read() == ap_const_lv8_40);
}

void top::thread_grp_fu_423_p2() {
    grp_fu_423_p2 = (!mux_sel_onehot_V.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(mux_sel_onehot_V.read() == ap_const_lv8_80);
}

void top::thread_grp_fu_429_p2() {
    grp_fu_429_p2 = (grp_fu_381_p2.read() | grp_fu_387_p2.read());
}

void top::thread_grp_leading_ones_brutefo_fu_346_ap_start() {
    grp_leading_ones_brutefo_fu_346_ap_start = grp_leading_ones_brutefo_fu_346_ap_start_reg.read();
}

void top::thread_grp_leading_ones_fu_352_ap_start() {
    grp_leading_ones_fu_352_ap_start = grp_leading_ones_fu_352_ap_start_reg.read();
}

void top::thread_icmp_ln14_1_fu_960_p2() {
    icmp_ln14_1_fu_960_p2 = (!max_in_2.read().is_01() || !select_ln14_fu_952_p3.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_2.read()) > sc_bigint<32>(select_ln14_fu_952_p3.read()));
}

void top::thread_icmp_ln14_2_fu_1183_p2() {
    icmp_ln14_2_fu_1183_p2 = (!max_in_3.read().is_01() || !phi_ln14_1_i_fu_1169_p10.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_3.read()) > sc_bigint<32>(phi_ln14_1_i_fu_1169_p10.read()));
}

void top::thread_icmp_ln14_3_fu_1219_p2() {
    icmp_ln14_3_fu_1219_p2 = (!max_in_4.read().is_01() || !phi_ln14_2_i_reg_1460.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_4.read()) > sc_bigint<32>(phi_ln14_2_i_reg_1460.read()));
}

void top::thread_icmp_ln14_4_fu_1249_p2() {
    icmp_ln14_4_fu_1249_p2 = (!max_in_5.read().is_01() || !phi_ln14_3_i_fu_1231_p10.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_5.read()) > sc_bigint<32>(phi_ln14_3_i_fu_1231_p10.read()));
}

void top::thread_icmp_ln14_5_fu_1275_p2() {
    icmp_ln14_5_fu_1275_p2 = (!max_in_6.read().is_01() || !phi_ln14_4_i_fu_1261_p10.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_6.read()) > sc_bigint<32>(phi_ln14_4_i_fu_1261_p10.read()));
}

void top::thread_icmp_ln14_6_fu_1302_p2() {
    icmp_ln14_6_fu_1302_p2 = (!max_in_7.read().is_01() || !phi_ln14_5_i_fu_1289_p10.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_7.read()) > sc_bigint<32>(phi_ln14_5_i_fu_1289_p10.read()));
}

void top::thread_icmp_ln14_fu_946_p2() {
    icmp_ln14_fu_946_p2 = (!max_in_1.read().is_01() || !max_in_0.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_1.read()) > sc_bigint<32>(max_in_0.read()));
}

void top::thread_icmp_ln883_1_fu_918_p2() {
    icmp_ln883_1_fu_918_p2 = (!trunc_ln3_fu_908_p4.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln3_fu_908_p4.read() == ap_const_lv8_0);
}

void top::thread_icmp_ln883_2_fu_1038_p2() {
    icmp_ln883_2_fu_1038_p2 = (!trunc_ln1503_1_reg_1400.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln1503_1_reg_1400.read() == ap_const_lv4_0);
}

void top::thread_icmp_ln883_3_fu_1073_p2() {
    icmp_ln883_3_fu_1073_p2 = (!trunc_ln1503_2_fu_1063_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln1503_2_fu_1063_p4.read() == ap_const_lv2_0);
}

void top::thread_icmp_ln883_fu_890_p2() {
    icmp_ln883_fu_890_p2 = (!trunc_ln1_fu_880_p4.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln1_fu_880_p4.read() == ap_const_lv16_0);
}

void top::thread_icmp_ln8_1_fu_453_p2() {
    icmp_ln8_1_fu_453_p2 = (!max_in_2.read().is_01() || !max_in_3.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_2.read()) > sc_bigint<32>(max_in_3.read()));
}

void top::thread_icmp_ln8_2_fu_467_p2() {
    icmp_ln8_2_fu_467_p2 = (!m0_1_fu_445_p3.read().is_01() || !m1_2_fu_459_p3.read().is_01())? sc_lv<1>(): (sc_bigint<32>(m0_1_fu_445_p3.read()) > sc_bigint<32>(m1_2_fu_459_p3.read()));
}

void top::thread_icmp_ln8_3_fu_481_p2() {
    icmp_ln8_3_fu_481_p2 = (!max_in_4.read().is_01() || !max_in_5.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_4.read()) > sc_bigint<32>(max_in_5.read()));
}

void top::thread_icmp_ln8_4_fu_495_p2() {
    icmp_ln8_4_fu_495_p2 = (!max_in_6.read().is_01() || !max_in_7.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_6.read()) > sc_bigint<32>(max_in_7.read()));
}

void top::thread_icmp_ln8_5_fu_509_p2() {
    icmp_ln8_5_fu_509_p2 = (!m0_5_fu_487_p3.read().is_01() || !m1_5_fu_501_p3.read().is_01())? sc_lv<1>(): (sc_bigint<32>(m0_5_fu_487_p3.read()) > sc_bigint<32>(m1_5_fu_501_p3.read()));
}

void top::thread_icmp_ln8_6_fu_978_p2() {
    icmp_ln8_6_fu_978_p2 = (!m0_3_reg_1341.read().is_01() || !m1_6_reg_1347.read().is_01())? sc_lv<1>(): (sc_bigint<32>(m0_3_reg_1341.read()) > sc_bigint<32>(m1_6_reg_1347.read()));
}

void top::thread_icmp_ln8_fu_439_p2() {
    icmp_ln8_fu_439_p2 = (!max_in_0.read().is_01() || !max_in_1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(max_in_0.read()) > sc_bigint<32>(max_in_1.read()));
}

void top::thread_leadone_out_V() {
    if ((esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0))) {
        leadone_out_V = grp_leading_ones_fu_352_ap_return_1.read();
    } else if ((esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0))) {
        leadone_out_V = grp_leading_ones_brutefo_fu_346_ap_return_1.read();
    } else if ((esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0))) {
        leadone_out_V = ssdm_int_V_write_ass_fu_1137_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_3))) {
        leadone_out_V = call_ret_i_leading_ones_32_s_fu_340_ap_return_1.read();
    } else {
        leadone_out_V = "XXXXX";
    }
}

void top::thread_leadone_out_V_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_3)) || 
         (esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0)))) {
        leadone_out_V_ap_vld = ap_const_logic_1;
    } else {
        leadone_out_V_ap_vld = ap_const_logic_0;
    }
}

void top::thread_leadone_ret() {
    if ((esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0))) {
        leadone_ret =  (sc_logic) (grp_leading_ones_fu_352_ap_return_0.read()[0]);
    } else if ((esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0))) {
        leadone_ret =  (sc_logic) (grp_leading_ones_brutefo_fu_346_ap_return_0.read()[0]);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2))) {
        leadone_ret =  (sc_logic) (flag_fu_873_p2.read()[0]);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_3))) {
        leadone_ret =  (sc_logic) (call_ret_i_leading_ones_32_s_fu_340_ap_return_0.read()[0]);
    } else {
        leadone_ret = sc_logic('X');
    }
}

void top::thread_leadone_ret_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_3)) || 
         (esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0)))) {
        leadone_ret_ap_vld = ap_const_logic_1;
    } else {
        leadone_ret_ap_vld = ap_const_logic_0;
    }
}

void top::thread_m0_1_fu_445_p3() {
    m0_1_fu_445_p3 = (!icmp_ln8_fu_439_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln8_fu_439_p2.read()[0].to_bool())? max_in_0.read(): max_in_1.read());
}

void top::thread_m0_3_fu_473_p3() {
    m0_3_fu_473_p3 = (!icmp_ln8_2_fu_467_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln8_2_fu_467_p2.read()[0].to_bool())? m0_1_fu_445_p3.read(): m1_2_fu_459_p3.read());
}

void top::thread_m0_5_fu_487_p3() {
    m0_5_fu_487_p3 = (!icmp_ln8_3_fu_481_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln8_3_fu_481_p2.read()[0].to_bool())? max_in_4.read(): max_in_5.read());
}

void top::thread_m1_2_fu_459_p3() {
    m1_2_fu_459_p3 = (!icmp_ln8_1_fu_453_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln8_1_fu_453_p2.read()[0].to_bool())? max_in_2.read(): max_in_3.read());
}

void top::thread_m1_5_fu_501_p3() {
    m1_5_fu_501_p3 = (!icmp_ln8_4_fu_495_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln8_4_fu_495_p2.read()[0].to_bool())? max_in_6.read(): max_in_7.read());
}

void top::thread_m1_6_fu_515_p3() {
    m1_6_fu_515_p3 = (!icmp_ln8_5_fu_509_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln8_5_fu_509_p2.read()[0].to_bool())? m0_5_fu_487_p3.read(): m1_5_fu_501_p3.read());
}

void top::thread_max_out() {
    if ((!esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()) && 
         !esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1) && 
         !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2) && 
         !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_3) && 
         !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_4) && 
         !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_5) && 
         !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_6) && 
         !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_7) && 
         !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_8) && 
         !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_9) && 
         !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_A) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        max_out = tmp_2_fu_1315_p10.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        max_out = select_ln8_7_fu_982_p3.read();
    } else {
        max_out =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void top::thread_max_out_ap_vld() {
    if (((!esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()) && 
          !esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1) && 
          !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2) && 
          !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_3) && 
          !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_4) && 
          !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_5) && 
          !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_6) && 
          !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_7) && 
          !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_8) && 
          !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_9) && 
          !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_A) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        max_out_ap_vld = ap_const_logic_1;
    } else {
        max_out_ap_vld = ap_const_logic_0;
    }
}

void top::thread_mode_read_read_fu_180_p2() {
    mode_read_read_fu_180_p2 = mode.read();
}

void top::thread_mux_ret_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mux_ret_V = select_ln879_7_fu_1008_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_4))) {
        mux_ret_V = select_ln5_fu_854_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_5))) {
        mux_ret_V = grp_fu_358_p10.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_6))) {
        mux_ret_V = select_ln6_7_fu_845_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_8))) {
        mux_ret_V = tmp_V_fu_576_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_9))) {
        mux_ret_V = tmp_8_fu_531_p10.read();
    } else {
        mux_ret_V =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void top::thread_mux_ret_V_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_9)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_8)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_6)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_5)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_4)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        mux_ret_V_ap_vld = ap_const_logic_1;
    } else {
        mux_ret_V_ap_vld = ap_const_logic_0;
    }
}

void top::thread_or_ln24_1_fu_1079_p2() {
    or_ln24_1_fu_1079_p2 = (select_ln24_5_fu_1055_p3.read() | ap_const_lv5_2);
}

void top::thread_or_ln24_2_fu_1121_p2() {
    or_ln24_2_fu_1121_p2 = (trunc_ln24_2_fu_1117_p1.read() | select_ln24_7_fu_1109_p3.read());
}

void top::thread_or_ln24_fu_1049_p2() {
    or_ln24_fu_1049_p2 = (select_ln24_3_fu_1031_p3.read() | ap_const_lv5_4);
}

void top::thread_or_ln6_1_fu_769_p2() {
    or_ln6_1_fu_769_p2 = (grp_fu_393_p2.read() | grp_fu_399_p2.read());
}

void top::thread_or_ln6_2_fu_783_p2() {
    or_ln6_2_fu_783_p2 = (grp_fu_405_p2.read() | grp_fu_411_p2.read());
}

void top::thread_or_ln6_3_fu_797_p2() {
    or_ln6_3_fu_797_p2 = (grp_fu_417_p2.read() | grp_fu_423_p2.read());
}

void top::thread_or_ln6_4_fu_811_p2() {
    or_ln6_4_fu_811_p2 = (grp_fu_429_p2.read() | or_ln6_1_fu_769_p2.read());
}

void top::thread_or_ln6_5_fu_825_p2() {
    or_ln6_5_fu_825_p2 = (or_ln6_2_fu_783_p2.read() | or_ln6_3_fu_797_p2.read());
}

void top::thread_or_ln6_6_fu_839_p2() {
    or_ln6_6_fu_839_p2 = (or_ln6_4_fu_811_p2.read() | or_ln6_5_fu_825_p2.read());
}

void top::thread_or_ln879_10_fu_993_p2() {
    or_ln879_10_fu_993_p2 = (or_ln879_7_reg_1363.read() | or_ln879_8_fu_989_p2.read());
}

void top::thread_or_ln879_11_fu_1003_p2() {
    or_ln879_11_fu_1003_p2 = (or_ln879_9_reg_1373.read() | or_ln879_10_fu_993_p2.read());
}

void top::thread_or_ln879_1_fu_609_p2() {
    or_ln879_1_fu_609_p2 = (grp_fu_429_p2.read() | grp_fu_393_p2.read());
}

void top::thread_or_ln879_2_fu_627_p2() {
    or_ln879_2_fu_627_p2 = (or_ln879_1_fu_609_p2.read() | grp_fu_399_p2.read());
}

void top::thread_or_ln879_3_fu_645_p2() {
    or_ln879_3_fu_645_p2 = (or_ln879_2_fu_627_p2.read() | grp_fu_405_p2.read());
}

void top::thread_or_ln879_4_fu_663_p2() {
    or_ln879_4_fu_663_p2 = (or_ln879_3_fu_645_p2.read() | grp_fu_411_p2.read());
}

void top::thread_or_ln879_5_fu_689_p2() {
    or_ln879_5_fu_689_p2 = (and_ln879_5_fu_675_p2.read() | and_ln879_4_fu_657_p2.read());
}

void top::thread_or_ln879_6_fu_703_p2() {
    or_ln879_6_fu_703_p2 = (and_ln879_3_fu_639_p2.read() | and_ln879_2_fu_621_p2.read());
}

void top::thread_or_ln879_7_fu_717_p2() {
    or_ln879_7_fu_717_p2 = (and_ln879_1_fu_603_p2.read() | and_ln879_fu_591_p2.read());
}

void top::thread_or_ln879_8_fu_989_p2() {
    or_ln879_8_fu_989_p2 = (icmp_ln879_reg_1353.read() | icmp_ln879_7_reg_1358.read());
}

void top::thread_or_ln879_9_fu_739_p2() {
    or_ln879_9_fu_739_p2 = (or_ln879_5_fu_689_p2.read() | or_ln879_6_fu_703_p2.read());
}

void top::thread_phi_ln14_1_i_fu_1169_p9() {
    phi_ln14_1_i_fu_1169_p9 = esl_zext<3,2>(select_ln14_1_reg_1441.read());
}

void top::thread_phi_ln14_2_i_fu_1200_p9() {
    phi_ln14_2_i_fu_1200_p9 = esl_zext<3,2>(select_ln14_2_fu_1189_p3.read());
}

void top::thread_phi_ln14_3_i_fu_1231_p9() {
    phi_ln14_3_i_fu_1231_p9 = (!icmp_ln14_3_fu_1219_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln14_3_fu_1219_p2.read()[0].to_bool())? ap_const_lv3_4: zext_ln14_2_reg_1455.read());
}

void top::thread_select_ln13_1_fu_1255_p3() {
    select_ln13_1_fu_1255_p3 = (!icmp_ln14_4_reg_1486.read()[0].is_01())? sc_lv<3>(): ((icmp_ln14_4_reg_1486.read()[0].to_bool())? ap_const_lv3_5: select_ln13_reg_1481.read());
}

void top::thread_select_ln13_fu_1224_p3() {
    select_ln13_fu_1224_p3 = (!icmp_ln14_3_fu_1219_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln14_3_fu_1219_p2.read()[0].to_bool())? ap_const_lv3_4: zext_ln14_2_reg_1455.read());
}

void top::thread_select_ln14_1_fu_970_p3() {
    select_ln14_1_fu_970_p3 = (!icmp_ln14_1_fu_960_p2.read()[0].is_01())? sc_lv<2>(): ((icmp_ln14_1_fu_960_p2.read()[0].to_bool())? ap_const_lv2_2: zext_ln14_fu_966_p1.read());
}

void top::thread_select_ln14_2_fu_1189_p3() {
    select_ln14_2_fu_1189_p3 = (!icmp_ln14_2_fu_1183_p2.read()[0].is_01())? sc_lv<2>(): ((icmp_ln14_2_fu_1183_p2.read()[0].to_bool())? ap_const_lv2_3: select_ln14_1_reg_1441.read());
}

void top::thread_select_ln14_3_fu_1281_p3() {
    select_ln14_3_fu_1281_p3 = (!icmp_ln14_5_fu_1275_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln14_5_fu_1275_p2.read()[0].to_bool())? ap_const_lv3_6: select_ln13_1_fu_1255_p3.read());
}

void top::thread_select_ln14_fu_952_p3() {
    select_ln14_fu_952_p3 = (!icmp_ln14_fu_946_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln14_fu_946_p2.read()[0].to_bool())? max_in_1.read(): max_in_0.read());
}

void top::thread_select_ln24_1_fu_1017_p3() {
    select_ln24_1_fu_1017_p3 = (!icmp_ln883_reg_1384.read()[0].is_01())? sc_lv<5>(): ((icmp_ln883_reg_1384.read()[0].to_bool())? ap_const_lv5_0: ap_const_lv5_10);
}

void top::thread_select_ln24_2_fu_924_p3() {
    select_ln24_2_fu_924_p3 = (!icmp_ln883_1_fu_918_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln883_1_fu_918_p2.read()[0].to_bool())? trunc_ln24_fu_904_p1.read(): trunc_ln3_fu_908_p4.read());
}

void top::thread_select_ln24_3_fu_1031_p3() {
    select_ln24_3_fu_1031_p3 = (!icmp_ln883_1_reg_1390.read()[0].is_01())? sc_lv<5>(): ((icmp_ln883_1_reg_1390.read()[0].to_bool())? select_ln24_1_fu_1017_p3.read(): select_ln25_fu_1024_p3.read());
}

void top::thread_select_ln24_4_fu_1043_p3() {
    select_ln24_4_fu_1043_p3 = (!icmp_ln883_2_fu_1038_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln883_2_fu_1038_p2.read()[0].to_bool())? trunc_ln24_1_reg_1395.read(): trunc_ln1503_1_reg_1400.read());
}

void top::thread_select_ln24_5_fu_1055_p3() {
    select_ln24_5_fu_1055_p3 = (!icmp_ln883_2_fu_1038_p2.read()[0].is_01())? sc_lv<5>(): ((icmp_ln883_2_fu_1038_p2.read()[0].to_bool())? select_ln24_3_fu_1031_p3.read(): or_ln24_fu_1049_p2.read());
}

void top::thread_select_ln24_6_fu_1085_p3() {
    select_ln24_6_fu_1085_p3 = (!icmp_ln883_3_fu_1073_p2.read()[0].is_01())? sc_lv<5>(): ((icmp_ln883_3_fu_1073_p2.read()[0].to_bool())? select_ln24_5_fu_1055_p3.read(): or_ln24_1_fu_1079_p2.read());
}

void top::thread_select_ln24_7_fu_1109_p3() {
    select_ln24_7_fu_1109_p3 = (!icmp_ln883_3_fu_1073_p2.read()[0].is_01())? sc_lv<1>(): ((icmp_ln883_3_fu_1073_p2.read()[0].to_bool())? tmp_4_fu_1093_p3.read(): tmp_9_fu_1101_p3.read());
}

void top::thread_select_ln24_fu_896_p3() {
    select_ln24_fu_896_p3 = (!icmp_ln883_fu_890_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln883_fu_890_p2.read()[0].to_bool())? trunc_ln37_fu_435_p1.read(): trunc_ln1_fu_880_p4.read());
}

void top::thread_select_ln25_fu_1024_p3() {
    select_ln25_fu_1024_p3 = (!icmp_ln883_reg_1384.read()[0].is_01())? sc_lv<5>(): ((icmp_ln883_reg_1384.read()[0].to_bool())? ap_const_lv5_8: ap_const_lv5_18);
}

void top::thread_select_ln5_fu_854_p0() {
    select_ln5_fu_854_p0 =  (sc_lv<1>) (mux_s.read());
}

void top::thread_select_ln5_fu_854_p3() {
    select_ln5_fu_854_p3 = (!select_ln5_fu_854_p0.read()[0].is_01())? sc_lv<8>(): ((select_ln5_fu_854_p0.read()[0].to_bool())? mux_in_1_V.read(): mux_in_0_V.read());
}

void top::thread_select_ln6_1_fu_761_p3() {
    select_ln6_1_fu_761_p3 = (!grp_fu_393_p2.read()[0].is_01())? sc_lv<8>(): ((grp_fu_393_p2.read()[0].to_bool())? mux_in_2_V.read(): mux_in_3_V.read());
}

void top::thread_select_ln6_2_fu_775_p3() {
    select_ln6_2_fu_775_p3 = (!grp_fu_405_p2.read()[0].is_01())? sc_lv<8>(): ((grp_fu_405_p2.read()[0].to_bool())? mux_in_4_V.read(): mux_in_5_V.read());
}

void top::thread_select_ln6_3_fu_789_p3() {
    select_ln6_3_fu_789_p3 = (!grp_fu_417_p2.read()[0].is_01())? sc_lv<8>(): ((grp_fu_417_p2.read()[0].to_bool())? mux_in_6_V.read(): mux_in_7_V.read());
}

void top::thread_select_ln6_4_fu_803_p3() {
    select_ln6_4_fu_803_p3 = (!grp_fu_429_p2.read()[0].is_01())? sc_lv<8>(): ((grp_fu_429_p2.read()[0].to_bool())? select_ln6_fu_753_p3.read(): select_ln6_1_fu_761_p3.read());
}

void top::thread_select_ln6_5_fu_817_p3() {
    select_ln6_5_fu_817_p3 = (!or_ln6_2_fu_783_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln6_2_fu_783_p2.read()[0].to_bool())? select_ln6_2_fu_775_p3.read(): select_ln6_3_fu_789_p3.read());
}

void top::thread_select_ln6_6_fu_831_p3() {
    select_ln6_6_fu_831_p3 = (!or_ln6_4_fu_811_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln6_4_fu_811_p2.read()[0].to_bool())? select_ln6_4_fu_803_p3.read(): select_ln6_5_fu_817_p3.read());
}

void top::thread_select_ln6_7_fu_845_p3() {
    select_ln6_7_fu_845_p3 = (!or_ln6_6_fu_839_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln6_6_fu_839_p2.read()[0].to_bool())? select_ln6_6_fu_831_p3.read(): ap_const_lv8_0);
}

void top::thread_select_ln6_fu_753_p3() {
    select_ln6_fu_753_p3 = (!grp_fu_381_p2.read()[0].is_01())? sc_lv<8>(): ((grp_fu_381_p2.read()[0].to_bool())? mux_in_0_V.read(): mux_in_1_V.read());
}

void top::thread_select_ln879_1_fu_695_p3() {
    select_ln879_1_fu_695_p3 = (!and_ln879_3_fu_639_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln879_3_fu_639_p2.read()[0].to_bool())? mux_in_4_V.read(): mux_in_3_V.read());
}

void top::thread_select_ln879_2_fu_709_p3() {
    select_ln879_2_fu_709_p3 = (!and_ln879_1_fu_603_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln879_1_fu_603_p2.read()[0].to_bool())? mux_in_2_V.read(): mux_in_1_V.read());
}

void top::thread_select_ln879_3_fu_723_p3() {
    select_ln879_3_fu_723_p3 = (!grp_fu_381_p2.read()[0].is_01())? sc_lv<8>(): ((grp_fu_381_p2.read()[0].to_bool())? mux_in_0_V.read(): mux_in_7_V.read());
}

void top::thread_select_ln879_4_fu_731_p3() {
    select_ln879_4_fu_731_p3 = (!or_ln879_5_fu_689_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln879_5_fu_689_p2.read()[0].to_bool())? select_ln879_fu_681_p3.read(): select_ln879_1_fu_695_p3.read());
}

void top::thread_select_ln879_5_fu_745_p3() {
    select_ln879_5_fu_745_p3 = (!or_ln879_7_fu_717_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln879_7_fu_717_p2.read()[0].to_bool())? select_ln879_2_fu_709_p3.read(): select_ln879_3_fu_723_p3.read());
}

void top::thread_select_ln879_6_fu_998_p3() {
    select_ln879_6_fu_998_p3 = (!or_ln879_9_reg_1373.read()[0].is_01())? sc_lv<8>(): ((or_ln879_9_reg_1373.read()[0].to_bool())? select_ln879_4_reg_1368.read(): select_ln879_5_reg_1379.read());
}

void top::thread_select_ln879_7_fu_1008_p3() {
    select_ln879_7_fu_1008_p3 = (!or_ln879_11_fu_1003_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln879_11_fu_1003_p2.read()[0].to_bool())? select_ln879_6_fu_998_p3.read(): ap_const_lv8_0);
}

void top::thread_select_ln879_fu_681_p3() {
    select_ln879_fu_681_p3 = (!and_ln879_5_fu_675_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln879_5_fu_675_p2.read()[0].to_bool())? mux_in_6_V.read(): mux_in_5_V.read());
}

void top::thread_select_ln8_7_fu_982_p3() {
    select_ln8_7_fu_982_p3 = (!icmp_ln8_6_fu_978_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln8_6_fu_978_p2.read()[0].to_bool())? m0_3_reg_1341.read(): m1_6_reg_1347.read());
}

void top::thread_select_ln8_fu_523_p0() {
    select_ln8_fu_523_p0 =  (sc_lv<1>) (mux_s.read());
}

void top::thread_ssdm_int_V_write_ass_fu_1137_p3() {
    ssdm_int_V_write_ass_fu_1137_p3 = esl_concat<4,1>(tmp_10_fu_1127_p4.read(), or_ln24_2_fu_1121_p2.read());
}

void top::thread_tmp_10_fu_1127_p4() {
    tmp_10_fu_1127_p4 = select_ln24_6_fu_1085_p3.read().range(4, 1);
}

void top::thread_tmp_2_fu_1315_p9() {
    tmp_2_fu_1315_p9 = (!icmp_ln14_6_fu_1302_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln14_6_fu_1302_p2.read()[0].to_bool())? ap_const_lv3_7: select_ln14_3_reg_1498.read());
}

void top::thread_tmp_4_fu_1093_p3() {
    tmp_4_fu_1093_p3 = select_ln24_4_fu_1043_p3.read().range(1, 1);
}

void top::thread_tmp_8_fu_531_p9() {
    tmp_8_fu_531_p9 = (!select_ln8_fu_523_p0.read()[0].is_01())? sc_lv<3>(): ((select_ln8_fu_523_p0.read()[0].to_bool())? mux_sel0_V.read(): mux_sel1_V.read());
}

void top::thread_tmp_9_fu_1101_p3() {
    tmp_9_fu_1101_p3 = select_ln24_4_fu_1043_p3.read().range(3, 3);
}

void top::thread_tmp_V_fu_576_p0() {
    tmp_V_fu_576_p0 =  (sc_lv<1>) (mux_s.read());
}

void top::thread_tmp_V_fu_576_p3() {
    tmp_V_fu_576_p3 = (!tmp_V_fu_576_p0.read()[0].is_01())? sc_lv<8>(): ((tmp_V_fu_576_p0.read()[0].to_bool())? grp_fu_358_p10.read(): tmp_7_fu_554_p10.read());
}

void top::thread_trunc_ln1503_2_fu_1063_p4() {
    trunc_ln1503_2_fu_1063_p4 = select_ln24_4_fu_1043_p3.read().range(3, 2);
}

void top::thread_trunc_ln1_fu_880_p4() {
    trunc_ln1_fu_880_p4 = leadone_in_V.read().range(31, 16);
}

void top::thread_trunc_ln24_1_fu_932_p1() {
    trunc_ln24_1_fu_932_p1 = select_ln24_2_fu_924_p3.read().range(4-1, 0);
}

void top::thread_trunc_ln24_2_fu_1117_p1() {
    trunc_ln24_2_fu_1117_p1 = select_ln24_6_fu_1085_p3.read().range(1-1, 0);
}

void top::thread_trunc_ln24_fu_904_p1() {
    trunc_ln24_fu_904_p1 = select_ln24_fu_896_p3.read().range(8-1, 0);
}

void top::thread_trunc_ln37_fu_435_p1() {
    trunc_ln37_fu_435_p1 = leadone_in_V.read().range(16-1, 0);
}

void top::thread_trunc_ln3_fu_908_p4() {
    trunc_ln3_fu_908_p4 = select_ln24_fu_896_p3.read().range(15, 8);
}

void top::thread_xor_ln879_1_fu_597_p2() {
    xor_ln879_1_fu_597_p2 = (grp_fu_429_p2.read() ^ ap_const_lv1_1);
}

void top::thread_xor_ln879_2_fu_615_p2() {
    xor_ln879_2_fu_615_p2 = (or_ln879_1_fu_609_p2.read() ^ ap_const_lv1_1);
}

void top::thread_xor_ln879_3_fu_633_p2() {
    xor_ln879_3_fu_633_p2 = (or_ln879_2_fu_627_p2.read() ^ ap_const_lv1_1);
}

void top::thread_xor_ln879_4_fu_651_p2() {
    xor_ln879_4_fu_651_p2 = (or_ln879_3_fu_645_p2.read() ^ ap_const_lv1_1);
}

void top::thread_xor_ln879_5_fu_669_p2() {
    xor_ln879_5_fu_669_p2 = (or_ln879_4_fu_663_p2.read() ^ ap_const_lv1_1);
}

void top::thread_xor_ln879_fu_585_p2() {
    xor_ln879_fu_585_p2 = (grp_fu_381_p2.read() ^ ap_const_lv1_1);
}

void top::thread_zext_ln14_2_fu_1196_p1() {
    zext_ln14_2_fu_1196_p1 = esl_zext<3,2>(select_ln14_2_fu_1189_p3.read());
}

void top::thread_zext_ln14_fu_966_p1() {
    zext_ln14_fu_966_p1 = esl_zext<2,1>(icmp_ln14_fu_946_p2.read());
}

void top::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && (((((esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_9) || 
      esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_8)) || 
     esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_6)) || 
    esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_5)) || 
   esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_4)) || 
  esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_3)))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && !esl_seteq<1,32,32>(ap_const_lv32_0, mode.read()) && !esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_3) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_4) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_5) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_6) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_7) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_8) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_9) && !esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_A))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && ((esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2) || 
   esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1)) || 
  esl_seteq<1,32,32>(ap_const_lv32_0, mode.read())))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_7))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_A))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_block_state4_on_subcall_done.read(), ap_const_boolean_0) && ((esl_seteq<1,32,32>(mode_read_read_fu_180_p2.read(), ap_const_lv32_2) || 
   esl_seteq<1,32,32>(mode.read(), ap_const_lv32_1)) || 
  esl_seteq<1,32,32>(ap_const_lv32_0, mode.read())))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<8>) ("XXXXXXXX");
            break;
    }
}

void top::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"leadone_in_V\" :  \"" << leadone_in_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"leadone_out_V\" :  \"" << leadone_out_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"leadone_out_V_ap_vld\" :  \"" << leadone_out_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"leadone_ret\" :  \"" << leadone_ret.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"leadone_ret_ap_vld\" :  \"" << leadone_ret_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_in_0_V\" :  \"" << mux_in_0_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_in_1_V\" :  \"" << mux_in_1_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_in_2_V\" :  \"" << mux_in_2_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_in_3_V\" :  \"" << mux_in_3_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_in_4_V\" :  \"" << mux_in_4_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_in_5_V\" :  \"" << mux_in_5_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_in_6_V\" :  \"" << mux_in_6_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_in_7_V\" :  \"" << mux_in_7_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_sel_onehot_V\" :  \"" << mux_sel_onehot_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_sel0_V\" :  \"" << mux_sel0_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_sel1_V\" :  \"" << mux_sel1_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mux_s\" :  \"" << mux_s.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mux_ret_V\" :  \"" << mux_ret_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mux_ret_V_ap_vld\" :  \"" << mux_ret_V_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"max_in_0\" :  \"" << max_in_0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"max_in_1\" :  \"" << max_in_1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"max_in_2\" :  \"" << max_in_2.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"max_in_3\" :  \"" << max_in_3.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"max_in_4\" :  \"" << max_in_4.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"max_in_5\" :  \"" << max_in_5.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"max_in_6\" :  \"" << max_in_6.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"max_in_7\" :  \"" << max_in_7.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"max_out\" :  \"" << max_out.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"max_out_ap_vld\" :  \"" << max_out_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mode\" :  \"" << mode.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

