-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1.3
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity imf3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (17 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (17 downto 0) );
end;


architecture behav of imf3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv35_0 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000000";
    constant ap_const_lv38_0 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_2 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal in_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal j : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal c_5_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_5_0_ce0 : STD_LOGIC;
    signal c_5_0_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal init_2 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal shift_reg_p0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal shift_reg_p0_ce0 : STD_LOGIC;
    signal shift_reg_p0_we0 : STD_LOGIC;
    signal shift_reg_p0_d0 : STD_LOGIC_VECTOR (37 downto 0);
    signal shift_reg_p0_q0 : STD_LOGIC_VECTOR (37 downto 0);
    signal c_5_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_5_1_ce0 : STD_LOGIC;
    signal c_5_1_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal shift_reg_p1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal shift_reg_p1_ce0 : STD_LOGIC;
    signal shift_reg_p1_we0 : STD_LOGIC;
    signal shift_reg_p1_d0 : STD_LOGIC_VECTOR (37 downto 0);
    signal shift_reg_p1_q0 : STD_LOGIC_VECTOR (37 downto 0);
    signal i_2_load_reg_392 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln23_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln23_reg_399 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_5_0_load_reg_419 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal c_5_1_load_reg_424 : STD_LOGIC_VECTOR (0 downto 0);
    signal inc_fu_162_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal inc_reg_429 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_Val2_s_reg_434 : STD_LOGIC_VECTOR (5 downto 0);
    signal ch_4_fu_171_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ch_4_reg_440 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_465 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal shift_reg_p0_load_reg_472 : STD_LOGIC_VECTOR (37 downto 0);
    signal grp_fu_380_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal m_reg_477 : STD_LOGIC_VECTOR (35 downto 0);
    signal trunc_ln30_1_fu_209_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal trunc_ln30_1_reg_482 : STD_LOGIC_VECTOR (34 downto 0);
    signal shift_reg_p1_load_reg_487 : STD_LOGIC_VECTOR (37 downto 0);
    signal m_1_fu_226_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal m_1_reg_492 : STD_LOGIC_VECTOR (34 downto 0);
    signal d_assign_reg_126 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln30_fu_156_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln30_1_fu_187_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln33_fu_248_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal inc_2_fu_368_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln40_fu_354_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln37_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_179_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln_fu_212_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal sext_ln46_2_fu_205_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal sub_ln46_fu_220_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_fu_242_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln30_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln30_fu_254_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln47_fu_261_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln30_1_fu_275_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln47_1_fu_282_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal trunc_ln30_fu_264_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal trunc_ln31_fu_285_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln36_fu_296_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln36_1_fu_301_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_4_fu_306_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_5_fu_316_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln37_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln40_fu_349_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln36_fu_326_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);

    component duc_mul_mul_18s_1bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;


    component imf3_c_5_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component imf3_shift_reg_p0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (37 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (37 downto 0) );
    end component;


    component imf3_c_5_1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    c_5_0_U : component imf3_c_5_0
    generic map (
        DataWidth => 18,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => c_5_0_address0,
        ce0 => c_5_0_ce0,
        q0 => c_5_0_q0);

    shift_reg_p0_U : component imf3_shift_reg_p0
    generic map (
        DataWidth => 38,
        AddressRange => 12,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => shift_reg_p0_address0,
        ce0 => shift_reg_p0_ce0,
        we0 => shift_reg_p0_we0,
        d0 => shift_reg_p0_d0,
        q0 => shift_reg_p0_q0);

    c_5_1_U : component imf3_c_5_1
    generic map (
        DataWidth => 1,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => c_5_1_address0,
        ce0 => c_5_1_ce0,
        q0 => c_5_1_q0);

    shift_reg_p1_U : component imf3_shift_reg_p0
    generic map (
        DataWidth => 38,
        AddressRange => 12,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => shift_reg_p1_address0,
        ce0 => shift_reg_p1_ce0,
        we0 => shift_reg_p1_we0,
        d0 => shift_reg_p1_d0,
        q0 => shift_reg_p1_q0);

    duc_mul_mul_18s_1bkb_U6 : component duc_mul_mul_18s_1bkb
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 36)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => c_5_0_load_reg_419,
        din1 => d_assign_reg_126,
        ce => ap_const_logic_1,
        dout => grp_fu_380_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv18_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    ap_return_preg <= select_ln36_fu_326_p3;
                end if; 
            end if;
        end if;
    end process;


    d_assign_reg_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                if ((icmp_ln23_fu_140_p2 = ap_const_lv1_0)) then 
                    d_assign_reg_126 <= in_1;
                elsif ((icmp_ln23_fu_140_p2 = ap_const_lv1_1)) then 
                    d_assign_reg_126 <= x;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                c_5_0_load_reg_419 <= c_5_0_q0;
                c_5_1_load_reg_424 <= c_5_1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                ch_4_reg_440 <= j(3 downto 3);
                inc_reg_429 <= inc_fu_162_p2;
                p_Val2_s_reg_434 <= j;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                i_2 <= inc_2_fu_368_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                i_2_load_reg_392 <= i_2;
                icmp_ln23_reg_399 <= icmp_ln23_fu_140_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln30_reg_465 <= icmp_ln30_fu_200_p2;
                m_1_reg_492 <= m_1_fu_226_p3;
                m_reg_477 <= grp_fu_380_p2;
                shift_reg_p0_load_reg_472 <= shift_reg_p0_q0;
                shift_reg_p1_load_reg_487 <= shift_reg_p1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln23_fu_140_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                in_1 <= x;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln37_fu_338_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                init_2 <= ap_const_lv1_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln30_reg_465 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                j <= select_ln40_fu_354_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln23_reg_399 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                trunc_ln30_1_reg_482 <= trunc_ln30_1_fu_209_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln36_1_fu_301_p2 <= std_logic_vector(unsigned(trunc_ln31_fu_285_p1) + unsigned(m_1_reg_492));
    add_ln36_fu_296_p2 <= std_logic_vector(unsigned(trunc_ln30_fu_264_p1) + unsigned(trunc_ln30_1_reg_482));
    add_ln40_fu_349_p2 <= std_logic_vector(unsigned(p_Val2_s_reg_434) + unsigned(ap_const_lv6_1));
    and_ln37_fu_338_p2 <= (icmp_ln37_fu_333_p2 and icmp_ln30_reg_465);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_CS_fsm_state5, select_ln36_fu_326_p3, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_return <= select_ln36_fu_326_p3;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    c_5_0_address0 <= zext_ln30_fu_156_p1(3 - 1 downto 0);

    c_5_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            c_5_0_ce0 <= ap_const_logic_1;
        else 
            c_5_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    c_5_1_address0 <= zext_ln30_fu_156_p1(3 - 1 downto 0);

    c_5_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            c_5_1_ce0 <= ap_const_logic_1;
        else 
            c_5_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ch_4_fu_171_p3 <= j(3 downto 3);
    icmp_ln23_fu_140_p2 <= "1" when (i_2 = ap_const_lv6_0) else "0";
    icmp_ln30_fu_200_p2 <= "1" when (i_2_load_reg_392 = ap_const_lv6_5) else "0";
    icmp_ln37_fu_333_p2 <= "1" when (p_Val2_s_reg_434 = ap_const_lv6_F) else "0";
    inc_2_fu_368_p3 <= 
        ap_const_lv6_0 when (icmp_ln30_reg_465(0) = '1') else 
        inc_reg_429;
    inc_fu_162_p2 <= std_logic_vector(unsigned(ap_const_lv6_1) + unsigned(i_2_load_reg_392));
    m_1_fu_226_p3 <= 
        sub_ln46_fu_220_p2 when (c_5_1_load_reg_424(0) = '1') else 
        ap_const_lv35_0;
    or_ln30_fu_237_p2 <= (init_2 or icmp_ln30_reg_465);
    select_ln30_1_fu_275_p3 <= 
        ap_const_lv38_0 when (or_ln30_fu_237_p2(0) = '1') else 
        shift_reg_p1_load_reg_487;
    select_ln30_fu_254_p3 <= 
        ap_const_lv38_0 when (or_ln30_fu_237_p2(0) = '1') else 
        shift_reg_p0_load_reg_472;
    select_ln36_fu_326_p3 <= 
        tmp_4_fu_306_p4 when (icmp_ln23_reg_399(0) = '1') else 
        tmp_5_fu_316_p4;
    select_ln40_fu_354_p3 <= 
        ap_const_lv6_0 when (icmp_ln37_fu_333_p2(0) = '1') else 
        add_ln40_fu_349_p2;
        sext_ln46_2_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_assign_reg_126),35));

        sext_ln47_1_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m_1_reg_492),38));

        sext_ln47_fu_261_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m_reg_477),38));


    shift_reg_p0_address0_assign_proc : process(ap_CS_fsm_state3, zext_ln30_1_fu_187_p1, zext_ln33_fu_248_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            shift_reg_p0_address0 <= zext_ln33_fu_248_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            shift_reg_p0_address0 <= zext_ln30_1_fu_187_p1(4 - 1 downto 0);
        else 
            shift_reg_p0_address0 <= "XXXX";
        end if; 
    end process;


    shift_reg_p0_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            shift_reg_p0_ce0 <= ap_const_logic_1;
        else 
            shift_reg_p0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    shift_reg_p0_d0 <= std_logic_vector(signed(sext_ln47_fu_261_p1) + signed(select_ln30_fu_254_p3));

    shift_reg_p0_we0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            shift_reg_p0_we0 <= ap_const_logic_1;
        else 
            shift_reg_p0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    shift_reg_p1_address0_assign_proc : process(ap_CS_fsm_state3, zext_ln30_1_fu_187_p1, zext_ln33_fu_248_p1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            shift_reg_p1_address0 <= zext_ln33_fu_248_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            shift_reg_p1_address0 <= zext_ln30_1_fu_187_p1(4 - 1 downto 0);
        else 
            shift_reg_p1_address0 <= "XXXX";
        end if; 
    end process;


    shift_reg_p1_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            shift_reg_p1_ce0 <= ap_const_logic_1;
        else 
            shift_reg_p1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    shift_reg_p1_d0 <= std_logic_vector(signed(sext_ln47_1_fu_282_p1) + signed(select_ln30_1_fu_275_p3));

    shift_reg_p1_we0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            shift_reg_p1_we0 <= ap_const_logic_1;
        else 
            shift_reg_p1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln_fu_212_p3 <= (d_assign_reg_126 & ap_const_lv17_0);
    sub_ln46_fu_220_p2 <= std_logic_vector(unsigned(shl_ln_fu_212_p3) - unsigned(sext_ln46_2_fu_205_p1));
    tmp_3_fu_179_p3 <= (inc_fu_162_p2 & ch_4_fu_171_p3);
    tmp_4_fu_306_p4 <= add_ln36_fu_296_p2(34 downto 17);
    tmp_5_fu_316_p4 <= add_ln36_1_fu_301_p2(34 downto 17);
    tmp_fu_242_p3 <= (i_2_load_reg_392 & ch_4_reg_440);
    trunc_ln30_1_fu_209_p1 <= grp_fu_380_p2(35 - 1 downto 0);
    trunc_ln30_fu_264_p1 <= select_ln30_fu_254_p3(35 - 1 downto 0);
    trunc_ln31_fu_285_p1 <= select_ln30_1_fu_275_p3(35 - 1 downto 0);
    zext_ln30_1_fu_187_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_179_p3),64));
    zext_ln30_fu_156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2),64));
    zext_ln33_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_242_p3),64));
end behav;
