# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/lab2/lab2.srcs/sources_1/bd/design_1/ip/design_1_fir_n11_maxi_0_0/design_1_fir_n11_maxi_0_0.xci
# IP: The module: 'design_1_fir_n11_maxi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/lab2/lab2.srcs/sources_1/bd/design_1/ip/design_1_fir_n11_maxi_0_0/constraints/fir_n11_maxi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_n11_maxi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado/lab2/lab2.srcs/sources_1/bd/design_1/ip/design_1_fir_n11_maxi_0_0/design_1_fir_n11_maxi_0_0.xci
# IP: The module: 'design_1_fir_n11_maxi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/lab2/lab2.srcs/sources_1/bd/design_1/ip/design_1_fir_n11_maxi_0_0/constraints/fir_n11_maxi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_n11_maxi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
